/*
This file is automatically generated
DO NOT MODIFY BY HAND
App
C Source
*/

#include "App.h"

#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Theme_LightBlue.h"
#include "stdlib.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
ESD_CORE_EXPORT void Esd_CoWidget_PopupSpinner();



void App__AppScreen__Initializer(App *context)
{
	AppScreen *object = (AppScreen *)context->AppScreen;
	AppScreen__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Root = 1;
	object->Widget.Active = 0;
	object->Widget.GlobalX = 0;
	object->Widget.GlobalY = 0;
	object->Widget.GlobalWidth = Esd_GetHost()->Width;
	object->Widget.GlobalHeight = Esd_GetHost()->Height;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
}

void App__AppScreen__Validate(App *context)
{
	if (!context->AppScreen)
	{
		context->AppScreen = (AppScreen *)esd_malloc(sizeof(AppScreen));
		if (context->AppScreen)
		{
			App__AppScreen__Initializer(context);
			context->AppScreen->Widget.Slots->Start(context->AppScreen);
		}
		else
		{
			eve_printf_debug("Out of memory (App__AppScreen__Validate)");
		}
	}
}

void App__AppScreen__Destroy(App *context)
{
	if (context->AppScreen)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->AppScreen, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->AppScreen);
		context->AppScreen->Widget.Slots->End(context->AppScreen);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->AppScreen);
		context->AppScreen = 0;
	}
}

void App__Initializer(App *context)
{
	context->Owner = 0;
	context->AppScreen = 0;
	App_Initialize(context);
}

void Ft_Esd_Theme_SetCurrent(Ft_Esd_Theme *);

void App_Initialize(App *context)
{
	void *owner = context->Owner;
}

void App_Start__Builtin(App *context)
{
	void *owner = context->Owner;
	App__AppScreen__Validate(context);
	Ft_Esd_Widget_SetActive(context->AppScreen, 1);
}

void App_Update__Builtin(App *context)
{
	void *owner = context->Owner;
	if (context->AppScreen && !context->AppScreen->Widget.Active)
	{
		App__AppScreen__Destroy(context);
	}
	if (context->AppScreen)
	{
		if (((Ft_Esd_Widget *)context->AppScreen)->Active)
		{
			((Ft_Esd_Widget *)context->AppScreen)->Slots->Update(context->AppScreen);
		}
	}
}

void App_Render__Builtin(App *context)
{
	void *owner = context->Owner;
	if (context->AppScreen)
	{
		if (((Ft_Esd_Widget *)context->AppScreen)->Active)
		{
			((Ft_Esd_Widget *)context->AppScreen)->Slots->Render(context->AppScreen);
		}
	}
}

void App_Idle__Builtin(App *context)
{
	void *owner = context->Owner;
	if (context->AppScreen)
	{
		if (((Ft_Esd_Widget *)context->AppScreen)->Active)
		{
			((Ft_Esd_Widget *)context->AppScreen)->Slots->Idle(context->AppScreen);
		}
	}
}

void App_End__Builtin(App *context)
{
	void *owner = context->Owner;
	App__AppScreen__Destroy(context); 
}

void App_Start(App *context)
{
	void *owner = context->Owner;
	App_Start__Builtin(context);
	App__AppScreen__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->AppScreen, 1);
	Ft_Esd_Theme * theme = Ft_Esd_Theme_LightBlue();
	Ft_Esd_Theme_SetCurrent(theme);
}

void App_Update(App *context)
{
	void *owner = context->Owner;
	App_Update__Builtin(context);
}

void App_Render(App *context)
{
	void *owner = context->Owner;
	Ft_Esd_Theme * theme_1 = Ft_Esd_Theme_LightBlue();
	Ft_Esd_Theme_SetCurrent(theme_1);
	App_Render__Builtin(context);
}

void App_Idle(App *context)
{
	void *owner = context->Owner;
	App_Idle__Builtin(context);
}

void App_End(App *context)
{
	void *owner = context->Owner;
	App_End__Builtin(context);
}

static App application;
static Esd_Context s_Esd;

void App__Start(App *context)
{
	App__Initializer(context);
	App_Start(context);
}

int main(int argc, char *argv[])
{
	Esd_Initialize();
	
	{
		Esd_Parameters ep;
		Esd_Defaults(&ep);
		ep.UserContext = &application;
		ep.Start = (Esd_Callback)App__Start;
		ep.Update = (Esd_Callback)App_Update;
		ep.Render = (Esd_Callback)App_Render;
		ep.Idle = (Esd_Callback)App_Idle;
		ep.End = (Esd_Callback)App_End;
#ifndef ESD_SIMULATION
#ifdef _WIN32
		const char *dataPath = "..\\..\\Data";
#else
		const char *dataPath = "../../Data";
#endif
#if defined(FT4222_PLATFORM) || defined(MPSSE_PLATFORM) || defined(BT8XXEMU_PLATFORM)
		struct stat st;
		if (stat(dataPath, &st) == 0)
			_chdir(dataPath);
#endif
#ifdef ESD_FLASH_FILES
		if (stat("Pages__Flash.bin", &st) == 0)
		{
#ifdef _WIN32
			wcscpy_s(ep.FlashFilePaths[ESD_FLASH_BT815], _countof(ep.FlashFilePaths[ESD_FLASH_BT815]), L"Pages__Flash.bin");
#if (EVE_SUPPORT_CHIPID >= EVE_BT820)
			wcscpy_s(ep.FlashFilePaths[ESD_FLASH_BT820], _countof(ep.FlashFilePaths[ESD_FLASH_BT820]), L"Pages__Flash.bin");
#elif (EVE_SUPPORT_CHIPID >= EVE_BT817)
			wcscpy_s(ep.FlashFilePaths[ESD_FLASH_BT817], _countof(ep.FlashFilePaths[ESD_FLASH_BT817]), L"Pages__Flash.bin");
#endif
#endif
		}
#endif
#endif
#ifdef ESD_MEMORYPOOL_ALLOCATOR
#ifdef ESD_MEMORYPOOL_MAXMEM
		ep.MaxPoolMemory = ESD_MEMORYPOOL_MAXMEM;
#endif
#ifdef ESD_MEMORYPOOL_IDEALMEM
		ep.IdealPoolMemory = ESD_MEMORYPOOL_IDEALMEM;
#endif
#endif
		if (!Esd_Open(&s_Esd, &ep))
			return EXIT_FAILURE;
	}
	Esd_Loop(&s_Esd);
	Esd_Close(&s_Esd);
	
	Esd_Release();
	return EXIT_SUCCESS;
}
#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	App Instance;
} App__ESD;


void *App__Create__ESD()
{
	App__ESD *context = (App__ESD *)esd_malloc(sizeof(App__ESD));
	if (context)
	{
		App__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (App__Create__ESD)");
	}
	return context;
}

void App__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
