/*
This file is automatically generated
DO NOT MODIFY BY HAND
AppScreen
C Source
*/

#include "AppScreen.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_AppScreen__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))AppScreen_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))AppScreen_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))AppScreen_End,
};

static void AppScreen_Usr_HeaderPage_Management_Signal__Signal(void *context);
static void AppScreen_Usr_HeaderPage_Status_Signal__Signal(void *context);
static void AppScreen_Usr_HeaderPage_Conflicts_Signal__Signal(void *context);
static void AppScreen_Usr_HeaderPage_Dashboard_Signal__Signal(void *context);
static void AppScreen_Usr_HeaderPage_Items_Signal__Signal(void *context);
static void AppScreen_Usr_PowerPage_Power_Signal__Signal(void *context);
static void AppScreen_Usr_PowerPage_Thermal_Signal__Signal(void *context);
static void AppScreen_Usr_PowerPage_Refrigeration_Signal__Signal(void *context);
static void AppScreen_Usr_ConfirmDialog_Close_Signal__Signal(void *context);
static void AppScreen_Usr_RefrigerationPage_Power_Signal__Signal(void *context);
static void AppScreen_Usr_RefrigerationPage_Thermal_Signal__Signal(void *context);
static void AppScreen_Usr_RefrigerationPage_Refrigeration_Signal__Signal(void *context);
static void AppScreen_Usr_ThermalPage_Power_Signal__Signal(void *context);
static void AppScreen_Usr_ThermalPage_Thermal_Signal__Signal(void *context);
static void AppScreen_Usr_ThermalPage_Refrigeration_Signal__Signal(void *context);
static void AppScreen_Main_Page_Activate_Window__Signal(void *context);

void AppScreen__Usr_HeaderPage__Initializer(AppScreen *context)
{
	Usr_HeaderPage *object = (Usr_HeaderPage *)context->Usr_HeaderPage;
	Usr_HeaderPage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->Management_Signal = AppScreen_Usr_HeaderPage_Management_Signal__Signal;
	object->Status_Signal = AppScreen_Usr_HeaderPage_Status_Signal__Signal;
	object->Conflicts_Signal = AppScreen_Usr_HeaderPage_Conflicts_Signal__Signal;
	object->Dashboard_Signal = AppScreen_Usr_HeaderPage_Dashboard_Signal__Signal;
	object->Items_Signal = AppScreen_Usr_HeaderPage_Items_Signal__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void AppScreen__Usr_HeaderPage__Validate(AppScreen *context)
{
	if (!context->Usr_HeaderPage)
	{
		context->Usr_HeaderPage = (Usr_HeaderPage *)esd_malloc(sizeof(Usr_HeaderPage));
		if (context->Usr_HeaderPage)
		{
			AppScreen__Usr_HeaderPage__Initializer(context);
			context->Usr_HeaderPage->Widget.Slots->Start(context->Usr_HeaderPage);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__Usr_HeaderPage__Validate)");
		}
	}
}

void AppScreen__Usr_HeaderPage__Destroy(AppScreen *context)
{
	if (context->Usr_HeaderPage)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_HeaderPage, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->Usr_HeaderPage);
		context->Usr_HeaderPage->Widget.Slots->End(context->Usr_HeaderPage);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->Usr_HeaderPage);
		context->Usr_HeaderPage = 0;
	}
}

void AppScreen__Switch_Page__Initializer(AppScreen *context)
{
	Ft_Esd_Layout_Switch *object = (Ft_Esd_Layout_Switch *)&context->Switch_Page;
	Ft_Esd_Layout_Switch__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 1;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void AppScreen__Usr_PowerPage__Initializer(AppScreen *context)
{
	Usr_PowerPage *object = (Usr_PowerPage *)context->Usr_PowerPage;
	Usr_PowerPage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->Power_Signal = AppScreen_Usr_PowerPage_Power_Signal__Signal;
	object->Thermal_Signal = AppScreen_Usr_PowerPage_Thermal_Signal__Signal;
	object->Refrigeration_Signal = AppScreen_Usr_PowerPage_Refrigeration_Signal__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Switch_Page);
}

void AppScreen__Usr_PowerPage__Validate(AppScreen *context)
{
	if (!context->Usr_PowerPage)
	{
		context->Usr_PowerPage = (Usr_PowerPage *)esd_malloc(sizeof(Usr_PowerPage));
		if (context->Usr_PowerPage)
		{
			AppScreen__Usr_PowerPage__Initializer(context);
			context->Usr_PowerPage->Widget.Slots->Start(context->Usr_PowerPage);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__Usr_PowerPage__Validate)");
		}
	}
}

void AppScreen__Usr_PowerPage__Destroy(AppScreen *context)
{
	if (context->Usr_PowerPage)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_PowerPage, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->Usr_PowerPage);
		context->Usr_PowerPage->Widget.Slots->End(context->Usr_PowerPage);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->Usr_PowerPage);
		context->Usr_PowerPage = 0;
	}
}

void AppScreen__Usr_ConflictsPage__Initializer(AppScreen *context)
{
	Usr_ConflictsPage *object = (Usr_ConflictsPage *)context->Usr_ConflictsPage;
	Usr_ConflictsPage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Switch_Page);
}

void AppScreen__Usr_ConflictsPage__Validate(AppScreen *context)
{
	if (!context->Usr_ConflictsPage)
	{
		context->Usr_ConflictsPage = (Usr_ConflictsPage *)esd_malloc(sizeof(Usr_ConflictsPage));
		if (context->Usr_ConflictsPage)
		{
			AppScreen__Usr_ConflictsPage__Initializer(context);
			context->Usr_ConflictsPage->Widget.Slots->Start(context->Usr_ConflictsPage);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__Usr_ConflictsPage__Validate)");
		}
	}
}

void AppScreen__Usr_ConflictsPage__Destroy(AppScreen *context)
{
	if (context->Usr_ConflictsPage)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ConflictsPage, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->Usr_ConflictsPage);
		context->Usr_ConflictsPage->Widget.Slots->End(context->Usr_ConflictsPage);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->Usr_ConflictsPage);
		context->Usr_ConflictsPage = 0;
	}
}

void AppScreen__Usr_ItemPage__Initializer(AppScreen *context)
{
	Usr_ItemPage *object = (Usr_ItemPage *)context->Usr_ItemPage;
	Usr_ItemPage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Switch_Page);
}

void AppScreen__Usr_ItemPage__Validate(AppScreen *context)
{
	if (!context->Usr_ItemPage)
	{
		context->Usr_ItemPage = (Usr_ItemPage *)esd_malloc(sizeof(Usr_ItemPage));
		if (context->Usr_ItemPage)
		{
			AppScreen__Usr_ItemPage__Initializer(context);
			context->Usr_ItemPage->Widget.Slots->Start(context->Usr_ItemPage);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__Usr_ItemPage__Validate)");
		}
	}
}

void AppScreen__Usr_ItemPage__Destroy(AppScreen *context)
{
	if (context->Usr_ItemPage)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ItemPage, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->Usr_ItemPage);
		context->Usr_ItemPage->Widget.Slots->End(context->Usr_ItemPage);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->Usr_ItemPage);
		context->Usr_ItemPage = 0;
	}
}

void AppScreen__Usr_ManagementPage__Initializer(AppScreen *context)
{
	Usr_ManagementPage *object = (Usr_ManagementPage *)context->Usr_ManagementPage;
	Usr_ManagementPage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Switch_Page);
}

void AppScreen__Usr_ManagementPage__Validate(AppScreen *context)
{
	if (!context->Usr_ManagementPage)
	{
		context->Usr_ManagementPage = (Usr_ManagementPage *)esd_malloc(sizeof(Usr_ManagementPage));
		if (context->Usr_ManagementPage)
		{
			AppScreen__Usr_ManagementPage__Initializer(context);
			context->Usr_ManagementPage->Widget.Slots->Start(context->Usr_ManagementPage);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__Usr_ManagementPage__Validate)");
		}
	}
}

void AppScreen__Usr_ManagementPage__Destroy(AppScreen *context)
{
	if (context->Usr_ManagementPage)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ManagementPage, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->Usr_ManagementPage);
		context->Usr_ManagementPage->Widget.Slots->End(context->Usr_ManagementPage);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->Usr_ManagementPage);
		context->Usr_ManagementPage = 0;
	}
}

void AppScreen__Usr_ConfirmDialog__Initializer(AppScreen *context)
{
	Usr_ConfirmDialog *object = (Usr_ConfirmDialog *)context->Usr_ConfirmDialog;
	Usr_ConfirmDialog__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->Close_Signal = AppScreen_Usr_ConfirmDialog_Close_Signal__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Switch_Page);
}

void AppScreen__Usr_ConfirmDialog__Validate(AppScreen *context)
{
	if (!context->Usr_ConfirmDialog)
	{
		context->Usr_ConfirmDialog = (Usr_ConfirmDialog *)esd_malloc(sizeof(Usr_ConfirmDialog));
		if (context->Usr_ConfirmDialog)
		{
			AppScreen__Usr_ConfirmDialog__Initializer(context);
			context->Usr_ConfirmDialog->Widget.Slots->Start(context->Usr_ConfirmDialog);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__Usr_ConfirmDialog__Validate)");
		}
	}
}

void AppScreen__Usr_ConfirmDialog__Destroy(AppScreen *context)
{
	if (context->Usr_ConfirmDialog)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ConfirmDialog, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->Usr_ConfirmDialog);
		context->Usr_ConfirmDialog->Widget.Slots->End(context->Usr_ConfirmDialog);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->Usr_ConfirmDialog);
		context->Usr_ConfirmDialog = 0;
	}
}

void AppScreen__Usr_RefrigerationPage__Initializer(AppScreen *context)
{
	Usr_RefrigerationPage *object = (Usr_RefrigerationPage *)context->Usr_RefrigerationPage;
	Usr_RefrigerationPage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->Power_Signal = AppScreen_Usr_RefrigerationPage_Power_Signal__Signal;
	object->Thermal_Signal = AppScreen_Usr_RefrigerationPage_Thermal_Signal__Signal;
	object->Refrigeration_Signal = AppScreen_Usr_RefrigerationPage_Refrigeration_Signal__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Switch_Page);
}

void AppScreen__Usr_RefrigerationPage__Validate(AppScreen *context)
{
	if (!context->Usr_RefrigerationPage)
	{
		context->Usr_RefrigerationPage = (Usr_RefrigerationPage *)esd_malloc(sizeof(Usr_RefrigerationPage));
		if (context->Usr_RefrigerationPage)
		{
			AppScreen__Usr_RefrigerationPage__Initializer(context);
			context->Usr_RefrigerationPage->Widget.Slots->Start(context->Usr_RefrigerationPage);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__Usr_RefrigerationPage__Validate)");
		}
	}
}

void AppScreen__Usr_RefrigerationPage__Destroy(AppScreen *context)
{
	if (context->Usr_RefrigerationPage)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_RefrigerationPage, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->Usr_RefrigerationPage);
		context->Usr_RefrigerationPage->Widget.Slots->End(context->Usr_RefrigerationPage);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->Usr_RefrigerationPage);
		context->Usr_RefrigerationPage = 0;
	}
}

void AppScreen__Usr_ThermalPage__Initializer(AppScreen *context)
{
	Usr_ThermalPage *object = (Usr_ThermalPage *)context->Usr_ThermalPage;
	Usr_ThermalPage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->Power_Signal = AppScreen_Usr_ThermalPage_Power_Signal__Signal;
	object->Thermal_Signal = AppScreen_Usr_ThermalPage_Thermal_Signal__Signal;
	object->Refrigeration_Signal = AppScreen_Usr_ThermalPage_Refrigeration_Signal__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Switch_Page);
}

void AppScreen__Usr_ThermalPage__Validate(AppScreen *context)
{
	if (!context->Usr_ThermalPage)
	{
		context->Usr_ThermalPage = (Usr_ThermalPage *)esd_malloc(sizeof(Usr_ThermalPage));
		if (context->Usr_ThermalPage)
		{
			AppScreen__Usr_ThermalPage__Initializer(context);
			context->Usr_ThermalPage->Widget.Slots->Start(context->Usr_ThermalPage);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__Usr_ThermalPage__Validate)");
		}
	}
}

void AppScreen__Usr_ThermalPage__Destroy(AppScreen *context)
{
	if (context->Usr_ThermalPage)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ThermalPage, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->Usr_ThermalPage);
		context->Usr_ThermalPage->Widget.Slots->End(context->Usr_ThermalPage);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->Usr_ThermalPage);
		context->Usr_ThermalPage = 0;
	}
}

void AppScreen__Main_Page__Initializer(AppScreen *context)
{
	FirstPage *object = (FirstPage *)context->Main_Page;
	FirstPage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->Activate_Window = AppScreen_Main_Page_Activate_Window__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Switch_Page);
}

void AppScreen__Main_Page__Validate(AppScreen *context)
{
	if (!context->Main_Page)
	{
		context->Main_Page = (FirstPage *)esd_malloc(sizeof(FirstPage));
		if (context->Main_Page)
		{
			AppScreen__Main_Page__Initializer(context);
			context->Main_Page->Widget.Slots->Start(context->Main_Page);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__Main_Page__Validate)");
		}
	}
}

void AppScreen__Main_Page__Destroy(AppScreen *context)
{
	if (context->Main_Page)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Main_Page, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->Main_Page);
		context->Main_Page->Widget.Slots->End(context->Main_Page);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->Main_Page);
		context->Main_Page = 0;
	}
}

void AppScreen__Initializer(AppScreen *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = AppScreen_CLASSID;
	context->Widget.Slots = &s_AppScreen__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Usr_HeaderPage = 0;
	AppScreen__Switch_Page__Initializer(context);
	context->Usr_PowerPage = 0;
	context->Usr_ConflictsPage = 0;
	context->Usr_ItemPage = 0;
	context->Usr_ManagementPage = 0;
	context->Usr_ConfirmDialog = 0;
	context->Usr_RefrigerationPage = 0;
	context->Usr_ThermalPage = 0;
	context->Main_Page = 0;
}

void AppScreen_Start(AppScreen *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	AppScreen__Usr_HeaderPage__Validate(context);
	Ft_Esd_Widget_SetActive(context->Usr_HeaderPage, 1);
	AppScreen__Usr_PowerPage__Validate(context);
	Ft_Esd_Widget_SetActive(context->Usr_PowerPage, 1);
	AppScreen__Usr_ConflictsPage__Validate(context);
	Ft_Esd_Widget_SetActive(context->Usr_ConflictsPage, 1);
	AppScreen__Usr_ItemPage__Validate(context);
	Ft_Esd_Widget_SetActive(context->Usr_ItemPage, 1);
	AppScreen__Usr_ManagementPage__Validate(context);
	Ft_Esd_Widget_SetActive(context->Usr_ManagementPage, 1);
	AppScreen__Usr_ConfirmDialog__Validate(context);
	Ft_Esd_Widget_SetActive(context->Usr_ConfirmDialog, 1);
	AppScreen__Usr_RefrigerationPage__Validate(context);
	Ft_Esd_Widget_SetActive(context->Usr_RefrigerationPage, 1);
	AppScreen__Usr_ThermalPage__Validate(context);
	Ft_Esd_Widget_SetActive(context->Usr_ThermalPage, 1);
	AppScreen__Main_Page__Validate(context);
	Ft_Esd_Widget_SetActive(context->Main_Page, 1);
}

void AppScreen_Update(AppScreen *context)
{
	void *owner = context->Owner;
	if (context->Usr_HeaderPage && !context->Usr_HeaderPage->Widget.Active)
	{
		AppScreen__Usr_HeaderPage__Destroy(context);
	}
	if (context->Usr_PowerPage && !context->Usr_PowerPage->Widget.Active)
	{
		AppScreen__Usr_PowerPage__Destroy(context);
	}
	if (context->Usr_ConflictsPage && !context->Usr_ConflictsPage->Widget.Active)
	{
		AppScreen__Usr_ConflictsPage__Destroy(context);
	}
	if (context->Usr_ItemPage && !context->Usr_ItemPage->Widget.Active)
	{
		AppScreen__Usr_ItemPage__Destroy(context);
	}
	if (context->Usr_ManagementPage && !context->Usr_ManagementPage->Widget.Active)
	{
		AppScreen__Usr_ManagementPage__Destroy(context);
	}
	if (context->Usr_ConfirmDialog && !context->Usr_ConfirmDialog->Widget.Active)
	{
		AppScreen__Usr_ConfirmDialog__Destroy(context);
	}
	if (context->Usr_RefrigerationPage && !context->Usr_RefrigerationPage->Widget.Active)
	{
		AppScreen__Usr_RefrigerationPage__Destroy(context);
	}
	if (context->Usr_ThermalPage && !context->Usr_ThermalPage->Widget.Active)
	{
		AppScreen__Usr_ThermalPage__Destroy(context);
	}
	if (context->Main_Page && !context->Main_Page->Widget.Active)
	{
		AppScreen__Main_Page__Destroy(context);
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void AppScreen_End(AppScreen *context)
{
	void *owner = context->Owner;
	AppScreen__Usr_HeaderPage__Destroy(context); 
	AppScreen__Usr_PowerPage__Destroy(context); 
	AppScreen__Usr_ConflictsPage__Destroy(context); 
	AppScreen__Usr_ItemPage__Destroy(context); 
	AppScreen__Usr_ManagementPage__Destroy(context); 
	AppScreen__Usr_ConfirmDialog__Destroy(context); 
	AppScreen__Usr_RefrigerationPage__Destroy(context); 
	AppScreen__Usr_ThermalPage__Destroy(context); 
	AppScreen__Main_Page__Destroy(context); 
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Switch_Page); 
}

void AppScreen_Usr_HeaderPage_Management_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_ManagementPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ManagementPage, 1);
}

void AppScreen_Usr_HeaderPage_Status_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_PowerPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_PowerPage, 1);
}

void AppScreen_Usr_HeaderPage_Conflicts_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_ConflictsPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ConflictsPage, 1);
}

void AppScreen_Usr_HeaderPage_Dashboard_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Main_Page__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Main_Page, 1);
}

void AppScreen_Usr_HeaderPage_Items_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_ItemPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ItemPage, 1);
}

void AppScreen_Usr_PowerPage_Power_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_PowerPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_PowerPage, 1);
}

void AppScreen_Usr_PowerPage_Thermal_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_ThermalPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ThermalPage, 1);
}

void AppScreen_Usr_PowerPage_Refrigeration_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_RefrigerationPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_RefrigerationPage, 1);
}

void AppScreen_Usr_ConfirmDialog_Close_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Main_Page__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Main_Page, 1);
}

void AppScreen_Usr_RefrigerationPage_Power_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_PowerPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_PowerPage, 1);
}

void AppScreen_Usr_RefrigerationPage_Thermal_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_ThermalPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ThermalPage, 1);
}

void AppScreen_Usr_RefrigerationPage_Refrigeration_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_RefrigerationPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_RefrigerationPage, 1);
}

void AppScreen_Usr_ThermalPage_Power_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_PowerPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_PowerPage, 1);
}

void AppScreen_Usr_ThermalPage_Thermal_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_ThermalPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ThermalPage, 1);
}

void AppScreen_Usr_ThermalPage_Refrigeration_Signal__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_RefrigerationPage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_RefrigerationPage, 1);
}

void AppScreen_Main_Page_Activate_Window__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__Usr_ConfirmDialog__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->Usr_ConfirmDialog, 1);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	AppScreen Instance;
} AppScreen__ESD;


void *AppScreen__Create__ESD()
{
	AppScreen__ESD *context = (AppScreen__ESD *)esd_malloc(sizeof(AppScreen__ESD));
	if (context)
	{
		AppScreen__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (AppScreen__Create__ESD)");
	}
	return context;
}

void AppScreen__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
