/*
This file is automatically generated
battery
C Source
*/

#include "battery.h"

#include "Ft_Gpu.h"

Ft_Esd_BitmapInfo battery__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 1686, /* Padded to 1688, REPEAT will not work as expected */
	.Height = 1920,
	.Format = COMPRESSED_RGBA_ASTC_8x8_KHR,
	.Stride = 128,
	.Size = 810240,
	.File = "battery.astc",
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Type = ESD_RESOURCE_FILE,
};

Ft_Esd_BitmapCell battery(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &battery__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell battery_0__Get__ESD() { return battery(0); }
#endif

/* end of file */
