/*
This file is automatically generated
battery
Header
*/

#ifndef battery__H
#define battery__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell battery(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo battery__Info;

ESD_FUNCTION(battery_0, Type = Ft_Esd_BitmapCell, DisplayName = "battery", Include = "battery.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define battery_0() ((Ft_Esd_BitmapCell){ .Info = &battery__Info, .Cell = 0 })

#endif /* battery__H */

/* end of file */
