/*
This file is automatically generated
DO NOT MODIFY BY HAND
FirstPage
Header
*/

#ifndef FirstPage__H
#define FirstPage__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"
#include "Usr_ScrollPanelVert.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define FirstPage_CLASSID 0x72AE16B4
ESD_SYMBOL(FirstPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(FirstPage, Include = "FirstPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(Activate_Window)
	void(* Activate_Window)(void *context);
	Ft_Esd_Layout_Fixed Fixed_Position;
	Usr_ScrollPanelVert Vertical_Scroll_Panel;
	Ft_Esd_PushButton First_Page;
	Ft_Esd_PushButton Previous_Page;
	Ft_Esd_PushButton Last_Page;
	Ft_Esd_PushButton Next_Page;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_Label Health;
	Ft_Esd_Label Date_Added;
	Ft_Esd_Label Quantity;
	Ft_Esd_Label Name;
	Ft_Esd_Label Filter;
	Ft_Esd_PushButton Add_New;
} FirstPage;

void FirstPage__Initializer(FirstPage *context);

ESD_SLOT(Update)
void FirstPage_Update(FirstPage *context);

ESD_SLOT(End)
void FirstPage_End(FirstPage *context);

#endif /* FirstPage__H */

/* end of file */
