/*
This file is automatically generated
DO NOT MODIFY BY HAND
FirstPage
C Source
*/

#include "FirstPage.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static const char * FirstPage_First_Page_Text__Property(void *context) { return "< |"; }
static const char * FirstPage_Previous_Page_Text__Property(void *context) { return "<"; }
static const char * FirstPage_Last_Page_Text__Property(void *context) { return "| >"; }
static const char * FirstPage_Next_Page_Text__Property(void *context) { return ">"; }
static uint8_t FirstPage_ESD_Label_Font__Property(void *context) { return 29; }
static const char * FirstPage_ESD_Label_Text__Property(void *context) { return "0"; }
static uint8_t FirstPage_Health_Font__Property(void *context) { return 30; }
static const char * FirstPage_Health_Text__Property(void *context) { return "Health"; }
static uint8_t FirstPage_Date_Added_Font__Property(void *context) { return 30; }
static const char * FirstPage_Date_Added_Text__Property(void *context) { return "Date Added"; }
static uint8_t FirstPage_Quantity_Font__Property(void *context) { return 30; }
static const char * FirstPage_Quantity_Text__Property(void *context) { return "Quantity"; }
static uint8_t FirstPage_Name_Font__Property(void *context) { return 30; }
static const char * FirstPage_Name_Text__Property(void *context) { return "Name"; }
static const char * FirstPage_Filter_Text__Property(void *context) { return "Filters:"; }
static const char * FirstPage_Add_New_Text__Property(void *context) { return "Add New"; }

static Ft_Esd_WidgetSlots s_FirstPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))FirstPage_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))FirstPage_End,
};

static void FirstPage_Add_New_Pushed__Signal(void *context);

void FirstPage__Fixed_Position__Initializer(FirstPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void FirstPage__Vertical_Scroll_Panel__Initializer(FirstPage *context)
{
	Usr_ScrollPanelVert *object = (Usr_ScrollPanelVert *)&context->Vertical_Scroll_Panel;
	Usr_ScrollPanelVert__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 54;
	object->Widget.LocalY = 190;
	object->Widget.LocalWidth = 1180;
	object->Widget.LocalHeight = 554;
	object->ScrollBars = ESD_VISIBLE_ALWAYS;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__First_Page__Initializer(FirstPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->First_Page;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 462;
	object->Widget.LocalY = 755;
	object->Widget.LocalWidth = 54;
	object->Widget.LocalHeight = 36;
	object->Text = FirstPage_First_Page_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Previous_Page__Initializer(FirstPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Previous_Page;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 523;
	object->Widget.LocalY = 756;
	object->Widget.LocalWidth = 54;
	object->Widget.LocalHeight = 36;
	object->Text = FirstPage_Previous_Page_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Last_Page__Initializer(FirstPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Last_Page;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 700;
	object->Widget.LocalY = 756;
	object->Widget.LocalWidth = 54;
	object->Widget.LocalHeight = 36;
	object->Text = FirstPage_Last_Page_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Next_Page__Initializer(FirstPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Next_Page;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 638;
	object->Widget.LocalY = 756;
	object->Widget.LocalWidth = 54;
	object->Widget.LocalHeight = 36;
	object->Text = FirstPage_Next_Page_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__ESD_Label__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 600;
	object->Widget.LocalY = 760;
	object->Widget.LocalWidth = 40;
	object->Widget.LocalHeight = 36;
	object->Font = FirstPage_ESD_Label_Font__Property;
	object->Text = FirstPage_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Health__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Health;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 1100;
	object->Widget.LocalY = 123;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = FirstPage_Health_Font__Property;
	object->Text = FirstPage_Health_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Date_Added__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Date_Added;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 874;
	object->Widget.LocalY = 126;
	object->Widget.LocalWidth = 175;
	object->Widget.LocalHeight = 36;
	object->Font = FirstPage_Date_Added_Font__Property;
	object->Text = FirstPage_Date_Added_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Quantity__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Quantity;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 568;
	object->Widget.LocalY = 128;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = FirstPage_Quantity_Font__Property;
	object->Text = FirstPage_Quantity_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Name__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Name;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 185;
	object->Widget.LocalY = 128;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = FirstPage_Name_Font__Property;
	object->Text = FirstPage_Name_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Filter__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Filter;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 57;
	object->Widget.LocalY = 91;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Text = FirstPage_Filter_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Add_New__Initializer(FirstPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Add_New;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 1102;
	object->Widget.LocalY = 759;
	object->Widget.LocalWidth = 172;
	object->Widget.LocalHeight = 33;
	object->Text = FirstPage_Add_New_Text__Property;
	object->Pushed = FirstPage_Add_New_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Initializer(FirstPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = FirstPage_CLASSID;
	context->Widget.Slots = &s_FirstPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Activate_Window = Esd_Noop;
	FirstPage__Fixed_Position__Initializer(context);
	FirstPage__Vertical_Scroll_Panel__Initializer(context);
	FirstPage__First_Page__Initializer(context);
	FirstPage__Previous_Page__Initializer(context);
	FirstPage__Last_Page__Initializer(context);
	FirstPage__Next_Page__Initializer(context);
	FirstPage__ESD_Label__Initializer(context);
	FirstPage__Health__Initializer(context);
	FirstPage__Date_Added__Initializer(context);
	FirstPage__Quantity__Initializer(context);
	FirstPage__Name__Initializer(context);
	FirstPage__Filter__Initializer(context);
	FirstPage__Add_New__Initializer(context);
}

void FirstPage_Update_Signal(FirstPage *context);
void FirstPage_End_Signal(FirstPage *context);
void FirstPage_Add_New_Pushed(FirstPage *context);

void FirstPage_End__Builtin(FirstPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Vertical_Scroll_Panel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->First_Page); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Previous_Page); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Last_Page); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Next_Page); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Health); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Date_Added); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Quantity); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Name); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Filter); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Add_New); 
}

void FirstPage_Update(FirstPage *context)
{
	void *owner = context->Owner;
	FirstPage_Update_Signal(context);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void FirstPage_End(FirstPage *context)
{
	void *owner = context->Owner;
	FirstPage_End_Signal(context);
	FirstPage_End__Builtin(context);
}

void FirstPage_Add_New_Pushed__Signal(void *c)
{
	FirstPage *context = (FirstPage *)c;
	void *owner = context->Owner;
	FirstPage_Add_New_Pushed(context);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	FirstPage Instance;
} FirstPage__ESD;


void *FirstPage__Create__ESD()
{
	FirstPage__ESD *context = (FirstPage__ESD *)esd_malloc(sizeof(FirstPage__ESD));
	if (context)
	{
		FirstPage__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (FirstPage__Create__ESD)");
	}
	return context;
}

void FirstPage__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
