/*
This file is automatically generated
Picture1
C Source
*/

#include "Picture1.h"

#include "Ft_Gpu.h"

Ft_Esd_BitmapInfo Picture1__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 401, /* Padded to 404, REPEAT will not work as expected */
	.Height = 305, /* Padded to 308, REPEAT will not work as expected */
	.Format = COMPRESSED_RGBA_ASTC_4x4_KHR,
	.Stride = 64,
	.Size = 124432,
	.File = "Picture1.astc",
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Type = ESD_RESOURCE_FILE,
};

Ft_Esd_BitmapCell Picture1(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Picture1__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Picture1_0__Get__ESD() { return Picture1(0); }
#endif

/* end of file */
