/*
This file is automatically generated
Picture1
Header
*/

#ifndef Picture1__H
#define Picture1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell Picture1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo Picture1__Info;

ESD_FUNCTION(Picture1_0, Type = Ft_Esd_BitmapCell, DisplayName = "Picture1", Include = "Picture1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define Picture1_0() ((Ft_Esd_BitmapCell){ .Info = &Picture1__Info, .Cell = 0 })

#endif /* Picture1__H */

/* end of file */
