/*
This file is automatically generated
R
C Source
*/

#include "R.h"

#include "Ft_Gpu.h"

Ft_Esd_BitmapInfo R__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 1000,
	.Height = 1160,
	.Format = COMPRESSED_RGBA_ASTC_8x8_KHR,
	.Stride = 128,
	.Size = 290000,
	.File = "R.astc",
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Type = ESD_RESOURCE_FILE,
};

Ft_Esd_BitmapCell R(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &R__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell R_0__Get__ESD() { return R(0); }
#endif

/* end of file */
