/*
This file is automatically generated
R
Header
*/

#ifndef R__H
#define R__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell R(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo R__Info;

ESD_FUNCTION(R_0, Type = Ft_Esd_BitmapCell, DisplayName = "R", Include = "R.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define R_0() ((Ft_Esd_BitmapCell){ .Info = &R__Info, .Cell = 0 })

#endif /* R__H */

/* end of file */
