/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_ConfirmDialog
C Source
*/

#include "Usr_ConfirmDialog.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static Ft_Esd_BitmapCell Usr_ConfirmDialog_ESD_Image_BitmapCell__Property(void *context) { return Picture1_0(); }
static uint8_t Usr_ConfirmDialog_ESD_TextBox_Font__Property(void *context) { return 30; }
static Ft_Esd_Theme * Usr_ConfirmDialog_ESD_TextBox_Theme__Property(void *context) { return Ft_Esd_Theme_DarkOrange(); }
static cstring Usr_ConfirmDialog_ESD_TextBox_Text__Property(void *context) { return "Min Temp (survive):                                  2 \nMax Temp (survive):                                 8  \nMin Temp Monitored:                              1.8  \nMax Temp Monitored:                             8 \nDate Added:               2025-10-22 08:30am \n"; }
static const char * Usr_ConfirmDialog_Close_Text__Property(void *context) { return "Close"; }

static Ft_Esd_WidgetSlots s_Usr_ConfirmDialog__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_ConfirmDialog_End,
};

static void Usr_ConfirmDialog_Close_Pushed__Signal(void *context);

void Usr_ConfirmDialog__Fixed_Position__Initializer(Usr_ConfirmDialog *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_ConfirmDialog__ESD_Image__Initializer(Usr_ConfirmDialog *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 744;
	object->Widget.LocalY = 117;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = Usr_ConfirmDialog_ESD_Image_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ConfirmDialog__ESD_TextBox__Initializer(Usr_ConfirmDialog *context)
{
	Ft_Esd_TextBox *object = (Ft_Esd_TextBox *)&context->ESD_TextBox;
	Ft_Esd_TextBox__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 35;
	object->Widget.LocalY = 70;
	object->Widget.LocalWidth = 612;
	object->Widget.LocalHeight = 414;
	object->Font = Usr_ConfirmDialog_ESD_TextBox_Font__Property;
	object->Theme = Usr_ConfirmDialog_ESD_TextBox_Theme__Property;
	object->Text = Usr_ConfirmDialog_ESD_TextBox_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ConfirmDialog__Close__Initializer(Usr_ConfirmDialog *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Close;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 566;
	object->Widget.LocalY = 724;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Text = Usr_ConfirmDialog_Close_Text__Property;
	object->Pushed = Usr_ConfirmDialog_Close_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ConfirmDialog__Initializer(Usr_ConfirmDialog *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_ConfirmDialog_CLASSID;
	context->Widget.Slots = &s_Usr_ConfirmDialog__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Close_Signal = Esd_Noop;
	Usr_ConfirmDialog__Fixed_Position__Initializer(context);
	Usr_ConfirmDialog__ESD_Image__Initializer(context);
	Usr_ConfirmDialog__ESD_TextBox__Initializer(context);
	Usr_ConfirmDialog__Close__Initializer(context);
}

void Usr_ConfirmDialog_End(Usr_ConfirmDialog *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_TextBox); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Close); 
}

void Usr_ConfirmDialog_Close_Pushed__Signal(void *c)
{
	Usr_ConfirmDialog *context = (Usr_ConfirmDialog *)c;
	void *owner = context->Owner;
	context->Close_Signal(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_ConfirmDialog Instance;
} Usr_ConfirmDialog__ESD;


void *Usr_ConfirmDialog__Create__ESD()
{
	Usr_ConfirmDialog__ESD *context = (Usr_ConfirmDialog__ESD *)esd_malloc(sizeof(Usr_ConfirmDialog__ESD));
	if (context)
	{
		Usr_ConfirmDialog__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_ConfirmDialog__Create__ESD)");
	}
	return context;
}

void Usr_ConfirmDialog__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
