/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_RefrigerationPage
Header
*/

#ifndef Usr_RefrigerationPage__H
#define Usr_RefrigerationPage__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_Image.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_RangeSlider.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Toggle.h"
#include "Ft_Esd_Widget.h"
#include "R.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_RefrigerationPage_CLASSID 0x94E66DD4
ESD_SYMBOL(Usr_RefrigerationPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_RefrigerationPage, Include = "Usr_RefrigerationPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(Power_Signal)
	void(* Power_Signal)(void *context);
	ESD_SIGNAL(Thermal_Signal)
	void(* Thermal_Signal)(void *context);
	ESD_SIGNAL(Refrigeration_Signal)
	void(* Refrigeration_Signal)(void *context);
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_RangeSlider ESD_RangeSlider_1_1;
	Ft_Esd_RangeSlider ESD_RangeSlider_2;
	Ft_Esd_PushButton Refrigeration;
	Ft_Esd_RangeSlider ESD_RangeSlider_1;
	Ft_Esd_Label Back_Pump_Rate;
	Ft_Esd_RangeSlider ESD_RangeSlider;
	Ft_Esd_PushButton Thermal;
	Ft_Esd_Toggle Back_Toggle;
	Ft_Esd_PushButton Power;
	Ft_Esd_Label Back_Compressor_Rate_1;
	Ft_Esd_Label Front_Pump_Rate;
	Ft_Esd_Label Front_Compressor_Rate;
	Ft_Esd_Label Back_Status;
	Ft_Esd_Toggle Front_Toggle;
	Ft_Esd_Label Front_Status;
	Ft_Esd_Image Front_Refrigerator;
	Ft_Esd_Image Back_Refrigerator;
} Usr_RefrigerationPage;

void Usr_RefrigerationPage__Initializer(Usr_RefrigerationPage *context);

ESD_SLOT(End)
void Usr_RefrigerationPage_End(Usr_RefrigerationPage *context);

#endif /* Usr_RefrigerationPage__H */

/* end of file */
