/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_ItemPage
Header
*/

#ifndef Usr_ItemPage__H
#define Usr_ItemPage__H

#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_ItemPage_CLASSID 0xFDD7BF3C
ESD_SYMBOL(Usr_ItemPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_ItemPage, Include = "Usr_ItemPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
} Usr_ItemPage;

void Usr_ItemPage__Initializer(Usr_ItemPage *context);

#endif /* Usr_ItemPage__H */

/* end of file */
