/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_ThermalPage
Header
*/

#ifndef Usr_ThermalPage__H
#define Usr_ThermalPage__H

#include "Esd_Base.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Gauge.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Theme_LightBlue.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_ThermalPage_CLASSID 0x30B5B83F
ESD_SYMBOL(Usr_ThermalPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_ThermalPage, Include = "Usr_ThermalPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(Power_Signal)
	void(* Power_Signal)(void *context);
	ESD_SIGNAL(Thermal_Signal)
	void(* Thermal_Signal)(void *context);
	ESD_SIGNAL(Refrigeration_Signal)
	void(* Refrigeration_Signal)(void *context);
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_PushButton Refrigeration;
	Ft_Esd_PushButton Thermal;
	Ft_Esd_PushButton Power;
	Ft_Esd_Label Heatsink_Hot_Front;
	Ft_Esd_Gauge ESD_Gauge_3;
	Ft_Esd_Gauge ESD_Gauge_2;
	Ft_Esd_Gauge ESD_Gauge;
} Usr_ThermalPage;

void Usr_ThermalPage__Initializer(Usr_ThermalPage *context);

ESD_SLOT(End)
void Usr_ThermalPage_End(Usr_ThermalPage *context);

#endif /* Usr_ThermalPage__H */

/* end of file */
