/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_ThermalPage
C Source
*/

#include "Usr_ThermalPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static const char * Usr_ThermalPage_Refrigeration_Text__Property(void *context) { return "Refrigeration"; }
static ft_bool_t Usr_ThermalPage_Refrigeration_Primary__Property(void *context) { return 0; }
static const char * Usr_ThermalPage_Thermal_Text__Property(void *context) { return "Thermal"; }
static ft_bool_t Usr_ThermalPage_Thermal_Primary__Property(void *context) { return 1; }
static const char * Usr_ThermalPage_Power_Text__Property(void *context) { return "Power"; }
static ft_bool_t Usr_ThermalPage_Power_Primary__Property(void *context) { return 0; }
static Ft_Esd_Theme * Usr_ThermalPage_Heatsink_Hot_Front_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static uint8_t Usr_ThermalPage_Heatsink_Hot_Front_Font__Property(void *context) { return 30; }
static const char * Usr_ThermalPage_Heatsink_Hot_Front_Text__Property(void *context) { return "Heatsink Hot Front"; }

static Ft_Esd_WidgetSlots s_Usr_ThermalPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_ThermalPage_End,
};

static void Usr_ThermalPage_Refrigeration_Pushed__Signal(void *context);
static void Usr_ThermalPage_Thermal_Pushed__Signal(void *context);
static void Usr_ThermalPage_Power_Pushed__Signal(void *context);

void Usr_ThermalPage__Fixed_Position__Initializer(Usr_ThermalPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_ThermalPage__Refrigeration__Initializer(Usr_ThermalPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Refrigeration;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 550;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 250;
	object->Text = Usr_ThermalPage_Refrigeration_Text__Property;
	object->Primary = Usr_ThermalPage_Refrigeration_Primary__Property;
	object->Pushed = Usr_ThermalPage_Refrigeration_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ThermalPage__Thermal__Initializer(Usr_ThermalPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Thermal;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 300;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 250;
	object->Text = Usr_ThermalPage_Thermal_Text__Property;
	object->Primary = Usr_ThermalPage_Thermal_Primary__Property;
	object->Pushed = Usr_ThermalPage_Thermal_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ThermalPage__Power__Initializer(Usr_ThermalPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Power;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 50;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 250;
	object->Text = Usr_ThermalPage_Power_Text__Property;
	object->Primary = Usr_ThermalPage_Power_Primary__Property;
	object->Pushed = Usr_ThermalPage_Power_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ThermalPage__Heatsink_Hot_Front__Initializer(Usr_ThermalPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Heatsink_Hot_Front;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 280;
	object->Widget.LocalY = 182;
	object->Widget.LocalWidth = 320;
	object->Widget.LocalHeight = 36;
	object->Theme = Usr_ThermalPage_Heatsink_Hot_Front_Theme__Property;
	object->Font = Usr_ThermalPage_Heatsink_Hot_Front_Font__Property;
	object->Text = Usr_ThermalPage_Heatsink_Hot_Front_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ThermalPage__ESD_Gauge_3__Initializer(Usr_ThermalPage *context)
{
	Ft_Esd_Gauge *object = (Ft_Esd_Gauge *)&context->ESD_Gauge_3;
	Ft_Esd_Gauge__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 502;
	object->Widget.LocalY = 242;
	object->Widget.LocalWidth = 144;
	object->Widget.LocalHeight = 144;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ThermalPage__ESD_Gauge_2__Initializer(Usr_ThermalPage *context)
{
	Ft_Esd_Gauge *object = (Ft_Esd_Gauge *)&context->ESD_Gauge_2;
	Ft_Esd_Gauge__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 354;
	object->Widget.LocalY = 246;
	object->Widget.LocalWidth = 144;
	object->Widget.LocalHeight = 144;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ThermalPage__ESD_Gauge__Initializer(Usr_ThermalPage *context)
{
	Ft_Esd_Gauge *object = (Ft_Esd_Gauge *)&context->ESD_Gauge;
	Ft_Esd_Gauge__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 202;
	object->Widget.LocalY = 244;
	object->Widget.LocalWidth = 144;
	object->Widget.LocalHeight = 144;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_ThermalPage__Initializer(Usr_ThermalPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_ThermalPage_CLASSID;
	context->Widget.Slots = &s_Usr_ThermalPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Power_Signal = Esd_Noop;
	context->Thermal_Signal = Esd_Noop;
	context->Refrigeration_Signal = Esd_Noop;
	Usr_ThermalPage__Fixed_Position__Initializer(context);
	Usr_ThermalPage__Refrigeration__Initializer(context);
	Usr_ThermalPage__Thermal__Initializer(context);
	Usr_ThermalPage__Power__Initializer(context);
	Usr_ThermalPage__Heatsink_Hot_Front__Initializer(context);
	Usr_ThermalPage__ESD_Gauge_3__Initializer(context);
	Usr_ThermalPage__ESD_Gauge_2__Initializer(context);
	Usr_ThermalPage__ESD_Gauge__Initializer(context);
}

void Usr_ThermalPage_End(Usr_ThermalPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Refrigeration); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Thermal); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Power); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Heatsink_Hot_Front); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Gauge_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Gauge_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Gauge); 
}

void Usr_ThermalPage_Refrigeration_Pushed__Signal(void *c)
{
	Usr_ThermalPage *context = (Usr_ThermalPage *)c;
	void *owner = context->Owner;
	context->Refrigeration_Signal(owner);
}

void Usr_ThermalPage_Thermal_Pushed__Signal(void *c)
{
	Usr_ThermalPage *context = (Usr_ThermalPage *)c;
	void *owner = context->Owner;
	context->Thermal_Signal(owner);
}

void Usr_ThermalPage_Power_Pushed__Signal(void *c)
{
	Usr_ThermalPage *context = (Usr_ThermalPage *)c;
	void *owner = context->Owner;
	context->Power_Signal(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_ThermalPage Instance;
} Usr_ThermalPage__ESD;


void *Usr_ThermalPage__Create__ESD()
{
	Usr_ThermalPage__ESD *context = (Usr_ThermalPage__ESD *)esd_malloc(sizeof(Usr_ThermalPage__ESD));
	if (context)
	{
		Usr_ThermalPage__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_ThermalPage__Create__ESD)");
	}
	return context;
}

void Usr_ThermalPage__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
