/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_RefrigerationPage
C Source
*/

#include "Usr_RefrigerationPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_1_1_Max__Property(void *context) { return 10; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_1_1_Step__Property(void *context) { return 1; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_1_1_Value__Property(void *context) { return 8; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_2_Max__Property(void *context) { return 10; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_2_Step__Property(void *context) { return 1; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_2_Value__Property(void *context) { return 9; }
static const char * Usr_RefrigerationPage_Refrigeration_Text__Property(void *context) { return "Refrigeration"; }
static ft_bool_t Usr_RefrigerationPage_Refrigeration_Primary__Property(void *context) { return 1; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_1_Max__Property(void *context) { return 10; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_1_Step__Property(void *context) { return 1; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_1_Value__Property(void *context) { return 6; }
static uint8_t Usr_RefrigerationPage_Back_Pump_Rate_Font__Property(void *context) { return 30; }
static const char * Usr_RefrigerationPage_Back_Pump_Rate_Text__Property(void *context) { return "Pump Rate:"; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_Max__Property(void *context) { return 10; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_Step__Property(void *context) { return 1; }
static ft_int16_t Usr_RefrigerationPage_ESD_RangeSlider_Value__Property(void *context) { return 3; }
static const char * Usr_RefrigerationPage_Thermal_Text__Property(void *context) { return "Thermal"; }
static ft_bool_t Usr_RefrigerationPage_Thermal_Primary__Property(void *context) { return 0; }
static const char * Usr_RefrigerationPage_Back_Toggle_Text__Property(void *context) { return "ON                                  OFF"; }
static const char * Usr_RefrigerationPage_Power_Text__Property(void *context) { return "Power"; }
static ft_bool_t Usr_RefrigerationPage_Power_Primary__Property(void *context) { return 0; }
static uint8_t Usr_RefrigerationPage_Back_Compressor_Rate_1_Font__Property(void *context) { return 30; }
static const char * Usr_RefrigerationPage_Back_Compressor_Rate_1_Text__Property(void *context) { return "Compressor Rate:"; }
static uint8_t Usr_RefrigerationPage_Front_Pump_Rate_Font__Property(void *context) { return 30; }
static const char * Usr_RefrigerationPage_Front_Pump_Rate_Text__Property(void *context) { return "Pump Rate:"; }
static uint8_t Usr_RefrigerationPage_Front_Compressor_Rate_Font__Property(void *context) { return 30; }
static const char * Usr_RefrigerationPage_Front_Compressor_Rate_Text__Property(void *context) { return "Compressor Rate:"; }
static uint8_t Usr_RefrigerationPage_Back_Status_Font__Property(void *context) { return 30; }
static const char * Usr_RefrigerationPage_Back_Status_Text__Property(void *context) { return "Status:"; }
static const char * Usr_RefrigerationPage_Front_Toggle_Text__Property(void *context) { return "ON                                  OFF"; }
static uint8_t Usr_RefrigerationPage_Front_Status_Font__Property(void *context) { return 30; }
static const char * Usr_RefrigerationPage_Front_Status_Text__Property(void *context) { return "Status:"; }
static Ft_Esd_BitmapCell Usr_RefrigerationPage_Front_Refrigerator_BitmapCell__Property(void *context) { return R_0(); }
static Ft_Esd_BitmapCell Usr_RefrigerationPage_Back_Refrigerator_BitmapCell__Property(void *context) { return R_0(); }

static Ft_Esd_WidgetSlots s_Usr_RefrigerationPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_RefrigerationPage_End,
};

static void Usr_RefrigerationPage_Refrigeration_Pushed__Signal(void *context);
static void Usr_RefrigerationPage_Thermal_Pushed__Signal(void *context);
static void Usr_RefrigerationPage_Power_Pushed__Signal(void *context);

void Usr_RefrigerationPage__Fixed_Position__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_RefrigerationPage__ESD_RangeSlider_1_1__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_RangeSlider *object = (Ft_Esd_RangeSlider *)&context->ESD_RangeSlider_1_1;
	Ft_Esd_RangeSlider__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 884;
	object->Widget.LocalY = 672;
	object->Widget.LocalWidth = 318;
	object->Widget.LocalHeight = 30;
	object->Max = Usr_RefrigerationPage_ESD_RangeSlider_1_1_Max__Property;
	object->Step = Usr_RefrigerationPage_ESD_RangeSlider_1_1_Step__Property;
	object->Value = Usr_RefrigerationPage_ESD_RangeSlider_1_1_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__ESD_RangeSlider_2__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_RangeSlider *object = (Ft_Esd_RangeSlider *)&context->ESD_RangeSlider_2;
	Ft_Esd_RangeSlider__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 876;
	object->Widget.LocalY = 271;
	object->Widget.LocalWidth = 318;
	object->Widget.LocalHeight = 30;
	object->Max = Usr_RefrigerationPage_ESD_RangeSlider_2_Max__Property;
	object->Step = Usr_RefrigerationPage_ESD_RangeSlider_2_Step__Property;
	object->Value = Usr_RefrigerationPage_ESD_RangeSlider_2_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Refrigeration__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Refrigeration;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 550;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 250;
	object->Text = Usr_RefrigerationPage_Refrigeration_Text__Property;
	object->Primary = Usr_RefrigerationPage_Refrigeration_Primary__Property;
	object->Pushed = Usr_RefrigerationPage_Refrigeration_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__ESD_RangeSlider_1__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_RangeSlider *object = (Ft_Esd_RangeSlider *)&context->ESD_RangeSlider_1;
	Ft_Esd_RangeSlider__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 882;
	object->Widget.LocalY = 570;
	object->Widget.LocalWidth = 318;
	object->Widget.LocalHeight = 30;
	object->Max = Usr_RefrigerationPage_ESD_RangeSlider_1_Max__Property;
	object->Step = Usr_RefrigerationPage_ESD_RangeSlider_1_Step__Property;
	object->Value = Usr_RefrigerationPage_ESD_RangeSlider_1_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Back_Pump_Rate__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Back_Pump_Rate;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 516;
	object->Widget.LocalY = 668;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_RefrigerationPage_Back_Pump_Rate_Font__Property;
	object->Text = Usr_RefrigerationPage_Back_Pump_Rate_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__ESD_RangeSlider__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_RangeSlider *object = (Ft_Esd_RangeSlider *)&context->ESD_RangeSlider;
	Ft_Esd_RangeSlider__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 873;
	object->Widget.LocalY = 169;
	object->Widget.LocalWidth = 318;
	object->Widget.LocalHeight = 30;
	object->Max = Usr_RefrigerationPage_ESD_RangeSlider_Max__Property;
	object->Step = Usr_RefrigerationPage_ESD_RangeSlider_Step__Property;
	object->Value = Usr_RefrigerationPage_ESD_RangeSlider_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Thermal__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Thermal;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 300;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 250;
	object->Text = Usr_RefrigerationPage_Thermal_Text__Property;
	object->Primary = Usr_RefrigerationPage_Thermal_Primary__Property;
	object->Pushed = Usr_RefrigerationPage_Thermal_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Back_Toggle__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Toggle *object = (Ft_Esd_Toggle *)&context->Back_Toggle;
	Ft_Esd_Toggle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 880;
	object->Widget.LocalY = 460;
	object->Widget.LocalWidth = 104;
	object->Widget.LocalHeight = 52;
	object->Text = Usr_RefrigerationPage_Back_Toggle_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Power__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Power;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 50;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 250;
	object->Text = Usr_RefrigerationPage_Power_Text__Property;
	object->Primary = Usr_RefrigerationPage_Power_Primary__Property;
	object->Pushed = Usr_RefrigerationPage_Power_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Back_Compressor_Rate_1__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Back_Compressor_Rate_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 516;
	object->Widget.LocalY = 561;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_RefrigerationPage_Back_Compressor_Rate_1_Font__Property;
	object->Text = Usr_RefrigerationPage_Back_Compressor_Rate_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Front_Pump_Rate__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Front_Pump_Rate;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 507;
	object->Widget.LocalY = 274;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_RefrigerationPage_Front_Pump_Rate_Font__Property;
	object->Text = Usr_RefrigerationPage_Front_Pump_Rate_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Front_Compressor_Rate__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Front_Compressor_Rate;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 504;
	object->Widget.LocalY = 164;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_RefrigerationPage_Front_Compressor_Rate_Font__Property;
	object->Text = Usr_RefrigerationPage_Front_Compressor_Rate_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Back_Status__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Back_Status;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 513;
	object->Widget.LocalY = 451;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_RefrigerationPage_Back_Status_Font__Property;
	object->Text = Usr_RefrigerationPage_Back_Status_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Front_Toggle__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Toggle *object = (Ft_Esd_Toggle *)&context->Front_Toggle;
	Ft_Esd_Toggle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 871;
	object->Widget.LocalY = 87;
	object->Widget.LocalWidth = 104;
	object->Widget.LocalHeight = 52;
	object->Text = Usr_RefrigerationPage_Front_Toggle_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Front_Status__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Front_Status;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 499;
	object->Widget.LocalY = 68;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_RefrigerationPage_Front_Status_Font__Property;
	object->Text = Usr_RefrigerationPage_Front_Status_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Front_Refrigerator__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Front_Refrigerator;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 204;
	object->Widget.LocalY = 61;
	object->Widget.LocalWidth = -68;
	object->Widget.LocalHeight = -68;
	object->BitmapCell = Usr_RefrigerationPage_Front_Refrigerator_BitmapCell__Property;
	object->ScaleX = (0L * (1L << 16) + 0x3333L);
	object->ScaleY = (0L * (1L << 16) + 0x3333L);
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Back_Refrigerator__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Back_Refrigerator;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 205;
	object->Widget.LocalY = 446;
	object->Widget.LocalWidth = -68;
	object->Widget.LocalHeight = -68;
	object->BitmapCell = Usr_RefrigerationPage_Back_Refrigerator_BitmapCell__Property;
	object->ScaleX = (0L * (1L << 16) + 0x3333L);
	object->ScaleY = (0L * (1L << 16) + 0x3333L);
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_RefrigerationPage__Initializer(Usr_RefrigerationPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_RefrigerationPage_CLASSID;
	context->Widget.Slots = &s_Usr_RefrigerationPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Power_Signal = Esd_Noop;
	context->Thermal_Signal = Esd_Noop;
	context->Refrigeration_Signal = Esd_Noop;
	Usr_RefrigerationPage__Fixed_Position__Initializer(context);
	Usr_RefrigerationPage__ESD_RangeSlider_1_1__Initializer(context);
	Usr_RefrigerationPage__ESD_RangeSlider_2__Initializer(context);
	Usr_RefrigerationPage__Refrigeration__Initializer(context);
	Usr_RefrigerationPage__ESD_RangeSlider_1__Initializer(context);
	Usr_RefrigerationPage__Back_Pump_Rate__Initializer(context);
	Usr_RefrigerationPage__ESD_RangeSlider__Initializer(context);
	Usr_RefrigerationPage__Thermal__Initializer(context);
	Usr_RefrigerationPage__Back_Toggle__Initializer(context);
	Usr_RefrigerationPage__Power__Initializer(context);
	Usr_RefrigerationPage__Back_Compressor_Rate_1__Initializer(context);
	Usr_RefrigerationPage__Front_Pump_Rate__Initializer(context);
	Usr_RefrigerationPage__Front_Compressor_Rate__Initializer(context);
	Usr_RefrigerationPage__Back_Status__Initializer(context);
	Usr_RefrigerationPage__Front_Toggle__Initializer(context);
	Usr_RefrigerationPage__Front_Status__Initializer(context);
	Usr_RefrigerationPage__Front_Refrigerator__Initializer(context);
	Usr_RefrigerationPage__Back_Refrigerator__Initializer(context);
}

void Usr_RefrigerationPage_End(Usr_RefrigerationPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_RangeSlider_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_RangeSlider_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Refrigeration); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_RangeSlider_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Back_Pump_Rate); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_RangeSlider); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Thermal); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Back_Toggle); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Power); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Back_Compressor_Rate_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Front_Pump_Rate); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Front_Compressor_Rate); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Back_Status); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Front_Toggle); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Front_Status); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Front_Refrigerator); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Back_Refrigerator); 
}

void Usr_RefrigerationPage_Refrigeration_Pushed__Signal(void *c)
{
	Usr_RefrigerationPage *context = (Usr_RefrigerationPage *)c;
	void *owner = context->Owner;
	context->Refrigeration_Signal(owner);
}

void Usr_RefrigerationPage_Thermal_Pushed__Signal(void *c)
{
	Usr_RefrigerationPage *context = (Usr_RefrigerationPage *)c;
	void *owner = context->Owner;
	context->Thermal_Signal(owner);
}

void Usr_RefrigerationPage_Power_Pushed__Signal(void *c)
{
	Usr_RefrigerationPage *context = (Usr_RefrigerationPage *)c;
	void *owner = context->Owner;
	context->Power_Signal(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_RefrigerationPage Instance;
} Usr_RefrigerationPage__ESD;


void *Usr_RefrigerationPage__Create__ESD()
{
	Usr_RefrigerationPage__ESD *context = (Usr_RefrigerationPage__ESD *)esd_malloc(sizeof(Usr_RefrigerationPage__ESD));
	if (context)
	{
		Usr_RefrigerationPage__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_RefrigerationPage__Create__ESD)");
	}
	return context;
}

void Usr_RefrigerationPage__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
