/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_RowWidget
Header
*/

#ifndef Usr_RowWidget__H
#define Usr_RowWidget__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Layout_Linear.h"
#include "Ft_Esd_Math.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_RowWidget_CLASSID 0x371F6849
ESD_SYMBOL(Usr_RowWidget_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_RowWidget, Include = "Usr_RowWidget.h", Callback, X = 79, Y = 242, Width = 1121, Height = 76)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_INPUT(Column_1_Input, Type = char *)
	char *(* Column_1_Input)(void *context);
	ESD_INPUT(Column_2_Input, Type = char *)
	char *(* Column_2_Input)(void *context);
	ESD_INPUT(Column_3_Input, Type = char *)
	char *(* Column_3_Input)(void *context);
	ESD_INPUT(Column_4_Input, Type = char *)
	char *(* Column_4_Input)(void *context);
	Ft_Esd_Layout_Linear Linear_Layout;
	Ft_Esd_PushButton ESD_Push_Button_1;
	Ft_Esd_PushButton ESD_Push_Button_2;
	Ft_Esd_PushButton ESD_Push_Button_3;
	Ft_Esd_PushButton ESD_Push_Button_4;
} Usr_RowWidget;

void Usr_RowWidget__Initializer(Usr_RowWidget *context);

ESD_SLOT(Start)
void Usr_RowWidget_Start(Usr_RowWidget *context);

ESD_SLOT(Update)
void Usr_RowWidget_Update(Usr_RowWidget *context);

ESD_SLOT(Render)
void Usr_RowWidget_Render(Usr_RowWidget *context);

ESD_SLOT(Idle)
void Usr_RowWidget_Idle(Usr_RowWidget *context);

ESD_SLOT(End)
void Usr_RowWidget_End(Usr_RowWidget *context);

#endif /* Usr_RowWidget__H */

/* end of file */
