/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_RowWidget
C Source
*/

#include "Usr_RowWidget.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);
char * Usr_RowWidget_Column_1_Input__Default(void *context) { return ""; }
char * Usr_RowWidget_Column_2_Input__Default(void *context) { return ""; }
char * Usr_RowWidget_Column_3_Input__Default(void *context) { return ""; }
char * Usr_RowWidget_Column_4_Input__Default(void *context) { return ""; }

static const char * Usr_RowWidget_ESD_Push_Button_1_Text__Property(void *context);
static const char * Usr_RowWidget_ESD_Push_Button_2_Text__Property(void *context);
static const char * Usr_RowWidget_ESD_Push_Button_3_Text__Property(void *context);
static const char * Usr_RowWidget_ESD_Push_Button_4_Text__Property(void *context);

static Ft_Esd_WidgetSlots s_Usr_RowWidget__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Usr_RowWidget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_RowWidget_Update,
	(void(*)(void *))Usr_RowWidget_Render,
	(void(*)(void *))Usr_RowWidget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_RowWidget_End,
};


void Usr_RowWidget__Linear_Layout__Initializer(Usr_RowWidget *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 526;
	object->Widget.LocalY = 24;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_FILLFILL;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_RowWidget__ESD_Push_Button_1__Initializer(Usr_RowWidget *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->ESD_Push_Button_1;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 208;
	object->Widget.LocalY = 32;
	object->Widget.LocalWidth = 246;
	object->Widget.LocalHeight = 36;
	object->Text = Usr_RowWidget_ESD_Push_Button_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void Usr_RowWidget__ESD_Push_Button_2__Initializer(Usr_RowWidget *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->ESD_Push_Button_2;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 164;
	object->Widget.LocalY = 42;
	object->Widget.LocalWidth = 266;
	object->Widget.LocalHeight = 36;
	object->Text = Usr_RowWidget_ESD_Push_Button_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void Usr_RowWidget__ESD_Push_Button_3__Initializer(Usr_RowWidget *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->ESD_Push_Button_3;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 897;
	object->Widget.LocalY = 41;
	object->Widget.LocalWidth = 179;
	object->Widget.LocalHeight = 36;
	object->Text = Usr_RowWidget_ESD_Push_Button_3_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void Usr_RowWidget__ESD_Push_Button_4__Initializer(Usr_RowWidget *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->ESD_Push_Button_4;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 795;
	object->Widget.LocalY = 7;
	object->Widget.LocalWidth = 58;
	object->Widget.LocalHeight = 36;
	object->Text = Usr_RowWidget_ESD_Push_Button_4_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void Usr_RowWidget__Initializer(Usr_RowWidget *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_RowWidget_CLASSID;
	context->Widget.Slots = &s_Usr_RowWidget__Slots;
	context->Widget.LocalX = 79;
	context->Widget.LocalY = 242;
	context->Widget.LocalWidth = 1121;
	context->Widget.LocalHeight = 76;
	context->Column_1_Input = Usr_RowWidget_Column_1_Input__Default;
	context->Column_2_Input = Usr_RowWidget_Column_2_Input__Default;
	context->Column_3_Input = Usr_RowWidget_Column_3_Input__Default;
	context->Column_4_Input = Usr_RowWidget_Column_4_Input__Default;
	Usr_RowWidget__Linear_Layout__Initializer(context);
	Usr_RowWidget__ESD_Push_Button_1__Initializer(context);
	Usr_RowWidget__ESD_Push_Button_2__Initializer(context);
	Usr_RowWidget__ESD_Push_Button_3__Initializer(context);
	Usr_RowWidget__ESD_Push_Button_4__Initializer(context);
}

void Usr_RowWidget_End__Builtin(Usr_RowWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button_4); 
}

void Usr_RowWidget_Start(Usr_RowWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
}

void Usr_RowWidget_Update(Usr_RowWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void Usr_RowWidget_Render(Usr_RowWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Usr_RowWidget_Idle(Usr_RowWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Idle((Ft_Esd_Widget *)context); 
}

void Usr_RowWidget_End(Usr_RowWidget *context)
{
	void *owner = context->Owner;
	Usr_RowWidget_End__Builtin(context);
}

const char * Usr_RowWidget_ESD_Push_Button_1_Text__Property(void *c)
{
	Usr_RowWidget *context = (Usr_RowWidget *)c;
	void *owner = context->Owner;
	return context->Column_1_Input(owner);
}

const char * Usr_RowWidget_ESD_Push_Button_2_Text__Property(void *c)
{
	Usr_RowWidget *context = (Usr_RowWidget *)c;
	void *owner = context->Owner;
	return context->Column_2_Input(owner);
}

const char * Usr_RowWidget_ESD_Push_Button_3_Text__Property(void *c)
{
	Usr_RowWidget *context = (Usr_RowWidget *)c;
	void *owner = context->Owner;
	return context->Column_3_Input(owner);
}

const char * Usr_RowWidget_ESD_Push_Button_4_Text__Property(void *c)
{
	Usr_RowWidget *context = (Usr_RowWidget *)c;
	void *owner = context->Owner;
	return context->Column_4_Input(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_RowWidget Instance;
	char * Column_1_Input;
	char * Column_2_Input;
	char * Column_3_Input;
	char * Column_4_Input;
} Usr_RowWidget__ESD;

char * Usr_RowWidget__Get_Column_1_Input__ESD(void *context) { return ((Usr_RowWidget__ESD *)context)->Column_1_Input; }
void Usr_RowWidget__Set_Column_1_Input__ESD(void *context, char * value) { ((Usr_RowWidget__ESD *)context)->Column_1_Input = value; }
char * Usr_RowWidget__Get_Column_2_Input__ESD(void *context) { return ((Usr_RowWidget__ESD *)context)->Column_2_Input; }
void Usr_RowWidget__Set_Column_2_Input__ESD(void *context, char * value) { ((Usr_RowWidget__ESD *)context)->Column_2_Input = value; }
char * Usr_RowWidget__Get_Column_3_Input__ESD(void *context) { return ((Usr_RowWidget__ESD *)context)->Column_3_Input; }
void Usr_RowWidget__Set_Column_3_Input__ESD(void *context, char * value) { ((Usr_RowWidget__ESD *)context)->Column_3_Input = value; }
char * Usr_RowWidget__Get_Column_4_Input__ESD(void *context) { return ((Usr_RowWidget__ESD *)context)->Column_4_Input; }
void Usr_RowWidget__Set_Column_4_Input__ESD(void *context, char * value) { ((Usr_RowWidget__ESD *)context)->Column_4_Input = value; }

void *Usr_RowWidget__Create__ESD()
{
	Usr_RowWidget__ESD *context = (Usr_RowWidget__ESD *)esd_malloc(sizeof(Usr_RowWidget__ESD));
	if (context)
	{
		Usr_RowWidget__Initializer(&context->Instance);
		context->Instance.Owner = context;
		context->Column_1_Input = "";
		context->Instance.Column_1_Input = Usr_RowWidget__Get_Column_1_Input__ESD;
		context->Column_2_Input = "";
		context->Instance.Column_2_Input = Usr_RowWidget__Get_Column_2_Input__ESD;
		context->Column_3_Input = "";
		context->Instance.Column_3_Input = Usr_RowWidget__Get_Column_3_Input__ESD;
		context->Column_4_Input = "";
		context->Instance.Column_4_Input = Usr_RowWidget__Get_Column_4_Input__ESD;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_RowWidget__Create__ESD)");
	}
	return context;
}

void Usr_RowWidget__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
