/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_ConfirmDialog
Header
*/

#ifndef Usr_ConfirmDialog__H
#define Usr_ConfirmDialog__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_Image.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_TextBox.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Theme_DarkOrange.h"
#include "Ft_Esd_Widget.h"
#include "Picture1.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_ConfirmDialog_CLASSID 0x43866444
ESD_SYMBOL(Usr_ConfirmDialog_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_ConfirmDialog, Include = "Usr_ConfirmDialog.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(Close_Signal)
	void(* Close_Signal)(void *context);
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_Image ESD_Image;
	Ft_Esd_TextBox ESD_TextBox;
	Ft_Esd_PushButton Close;
} Usr_ConfirmDialog;

void Usr_ConfirmDialog__Initializer(Usr_ConfirmDialog *context);

ESD_SLOT(End)
void Usr_ConfirmDialog_End(Usr_ConfirmDialog *context);

#endif /* Usr_ConfirmDialog__H */

/* end of file */
