/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_ConflictsPage
Header
*/

#ifndef Usr_ConflictsPage__H
#define Usr_ConflictsPage__H

#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_ConflictsPage_CLASSID 0x954149A0
ESD_SYMBOL(Usr_ConflictsPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_ConflictsPage, Include = "Usr_ConflictsPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
} Usr_ConflictsPage;

void Usr_ConflictsPage__Initializer(Usr_ConflictsPage *context);

#endif /* Usr_ConflictsPage__H */

/* end of file */
