/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_HeaderPage
Header
*/

#ifndef Usr_HeaderPage__H
#define Usr_HeaderPage__H

#include "Esd_Base.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Theme_LightBlue.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_HeaderPage_CLASSID 0x498CD477
ESD_SYMBOL(Usr_HeaderPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_HeaderPage, Include = "Usr_HeaderPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(Management_Signal)
	void(* Management_Signal)(void *context);
	ESD_SIGNAL(Status_Signal)
	void(* Status_Signal)(void *context);
	ESD_SIGNAL(Conflicts_Signal)
	void(* Conflicts_Signal)(void *context);
	ESD_SIGNAL(Dashboard_Signal)
	void(* Dashboard_Signal)(void *context);
	ESD_SIGNAL(Items_Signal)
	void(* Items_Signal)(void *context);
	ESD_VARIABLE(Selected_Page, Type = int, Default = 0, Private)
	int Selected_Page;
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_PushButton Conflicts;
	Ft_Esd_PushButton Management;
	Ft_Esd_PushButton Status;
	Ft_Esd_PushButton Items;
	Ft_Esd_PushButton Dashboard;
} Usr_HeaderPage;

void Usr_HeaderPage__Initializer(Usr_HeaderPage *context);

ESD_SLOT(End)
void Usr_HeaderPage_End(Usr_HeaderPage *context);

#endif /* Usr_HeaderPage__H */

/* end of file */
