/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_StatusPage
C Source
*/

#include "Usr_StatusPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static const char * Usr_StatusPage_Refrigeration_Text__Property(void *context) { return "Refrigeration"; }
static const char * Usr_StatusPage_Thermal_Text__Property(void *context) { return "Thermal"; }
static const char * Usr_StatusPage_Power_Text__Property(void *context) { return "Power"; }
static const char * Usr_StatusPage_Back_Button_Text__Property(void *context) { return "<Back"; }

static Ft_Esd_WidgetSlots s_Usr_StatusPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_StatusPage_End,
};

static void Usr_StatusPage_Refrigeration_Pushed__Signal(void *context);
static void Usr_StatusPage_Thermal_Pushed__Signal(void *context);
static void Usr_StatusPage_Power_Pushed__Signal(void *context);
static void Usr_StatusPage_Back_Button_Pushed__Signal(void *context);

void Usr_StatusPage__Fixed_Position__Initializer(Usr_StatusPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_StatusPage__Vertical_Scroll_Panel__Initializer(Usr_StatusPage *context)
{
	Usr_ScrollPanelVert *object = (Usr_ScrollPanelVert *)&context->Vertical_Scroll_Panel;
	Usr_ScrollPanelVert__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 570;
	object->Widget.LocalY = 494;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->ScrollBars = ESD_VISIBLE_ALWAYS;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_StatusPage__Usr_RowWidget__Initializer(Usr_StatusPage *context)
{
	Usr_RowWidget *object = (Usr_RowWidget *)&context->Usr_RowWidget;
	Usr_RowWidget__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 144;
	object->Widget.LocalY = 388;
	object->Widget.LocalWidth = 1121;
	object->Widget.LocalHeight = 76;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_StatusPage__Refrigeration__Initializer(Usr_StatusPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Refrigeration;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 540;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 260;
	object->Text = Usr_StatusPage_Refrigeration_Text__Property;
	object->Pushed = Usr_StatusPage_Refrigeration_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_StatusPage__Thermal__Initializer(Usr_StatusPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Thermal;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 280;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 260;
	object->Text = Usr_StatusPage_Thermal_Text__Property;
	object->Pushed = Usr_StatusPage_Thermal_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_StatusPage__Power__Initializer(Usr_StatusPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Power;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 30;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 260;
	object->Text = Usr_StatusPage_Power_Text__Property;
	object->Pushed = Usr_StatusPage_Power_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_StatusPage__Back_Button__Initializer(Usr_StatusPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Back_Button;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 30;
	object->Text = Usr_StatusPage_Back_Button_Text__Property;
	object->Pushed = Usr_StatusPage_Back_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_StatusPage__Initializer(Usr_StatusPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_StatusPage_CLASSID;
	context->Widget.Slots = &s_Usr_StatusPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Back_Signal = Esd_Noop;
	context->Power_Signal = Esd_Noop;
	context->Thermal_Signal = Esd_Noop;
	context->Refrigeration_Signal = Esd_Noop;
	Usr_StatusPage__Fixed_Position__Initializer(context);
	Usr_StatusPage__Vertical_Scroll_Panel__Initializer(context);
	Usr_StatusPage__Usr_RowWidget__Initializer(context);
	Usr_StatusPage__Refrigeration__Initializer(context);
	Usr_StatusPage__Thermal__Initializer(context);
	Usr_StatusPage__Power__Initializer(context);
	Usr_StatusPage__Back_Button__Initializer(context);
}

void Usr_StatusPage_End(Usr_StatusPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Vertical_Scroll_Panel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Usr_RowWidget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Refrigeration); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Thermal); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Power); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Back_Button); 
}

void Usr_StatusPage_Refrigeration_Pushed__Signal(void *c)
{
	Usr_StatusPage *context = (Usr_StatusPage *)c;
	void *owner = context->Owner;
	context->Refrigeration_Signal(owner);
}

void Usr_StatusPage_Thermal_Pushed__Signal(void *c)
{
	Usr_StatusPage *context = (Usr_StatusPage *)c;
	void *owner = context->Owner;
	context->Thermal_Signal(owner);
}

void Usr_StatusPage_Power_Pushed__Signal(void *c)
{
	Usr_StatusPage *context = (Usr_StatusPage *)c;
	void *owner = context->Owner;
	context->Power_Signal(owner);
}

void Usr_StatusPage_Back_Button_Pushed__Signal(void *c)
{
	Usr_StatusPage *context = (Usr_StatusPage *)c;
	void *owner = context->Owner;
	context->Back_Signal(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_StatusPage Instance;
} Usr_StatusPage__ESD;


void *Usr_StatusPage__Create__ESD()
{
	Usr_StatusPage__ESD *context = (Usr_StatusPage__ESD *)esd_malloc(sizeof(Usr_StatusPage__ESD));
	if (context)
	{
		Usr_StatusPage__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_StatusPage__Create__ESD)");
	}
	return context;
}

void Usr_StatusPage__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
