/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_ItemPage
C Source
*/

#include "Usr_ItemPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Usr_ItemPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Usr_ItemPage__Initializer(Usr_ItemPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_ItemPage_CLASSID;
	context->Widget.Slots = &s_Usr_ItemPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_ItemPage Instance;
} Usr_ItemPage__ESD;


void *Usr_ItemPage__Create__ESD()
{
	Usr_ItemPage__ESD *context = (Usr_ItemPage__ESD *)esd_malloc(sizeof(Usr_ItemPage__ESD));
	if (context)
	{
		Usr_ItemPage__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_ItemPage__Create__ESD)");
	}
	return context;
}

void Usr_ItemPage__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
