/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_PowerPage
C Source
*/

#include "Usr_PowerPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static uint8_t Usr_PowerPage_Battery_Label_4_Font__Property(void *context) { return 30; }
static const char * Usr_PowerPage_Battery_Label_4_Text__Property(void *context) { return "Battery 4:"; }
static uint8_t Usr_PowerPage_Battery_Label_3_Font__Property(void *context) { return 30; }
static const char * Usr_PowerPage_Battery_Label_3_Text__Property(void *context) { return "Battery 3:"; }
static uint8_t Usr_PowerPage_ESD_Label_2_2_2_1_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_2_2_2_1_Text__Property(void *context) { return "Temp: 50"; }
static uint8_t Usr_PowerPage_ESD_Label_2_2_2_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_2_2_2_Text__Property(void *context) { return "Temp: 50"; }
static uint8_t Usr_PowerPage_Battery_Label_2_Font__Property(void *context) { return 30; }
static const char * Usr_PowerPage_Battery_Label_2_Text__Property(void *context) { return "Battery 2:"; }
static uint8_t Usr_PowerPage_ESD_Label_2_1_1_1_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_2_1_1_1_Text__Property(void *context) { return "Charge Rate: 1.3"; }
static uint8_t Usr_PowerPage_ESD_Label_2_1_1_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_2_1_1_Text__Property(void *context) { return "Charge Rate: 1.3"; }
static uint8_t Usr_PowerPage_Battery_Label_1_Font__Property(void *context) { return 30; }
static const char * Usr_PowerPage_Battery_Label_1_Text__Property(void *context) { return "Battery 1:"; }
static uint8_t Usr_PowerPage_ESD_Label_2_2_1_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_2_2_1_Text__Property(void *context) { return "Temp: 50"; }
static uint8_t Usr_PowerPage_ESD_Label_1_2_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_1_2_Text__Property(void *context) { return "Charge Level : 82%"; }
static uint8_t Usr_PowerPage_ESD_Label_2_1_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_2_1_Text__Property(void *context) { return "Charge Rate: 1.3"; }
static const char * Usr_PowerPage_Refrigeration_Text__Property(void *context) { return "Refrigeration"; }
static ft_bool_t Usr_PowerPage_Refrigeration_Primary__Property(void *context) { return 0; }
static uint8_t Usr_PowerPage_ESD_Label_1_1_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_1_1_Text__Property(void *context) { return "Charge Level : 82%"; }
static uint8_t Usr_PowerPage_ESD_Label_2_2_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_2_2_Text__Property(void *context) { return "Temp: 50"; }
static const char * Usr_PowerPage_Thermal_Text__Property(void *context) { return "Thermal"; }
static ft_bool_t Usr_PowerPage_Thermal_Primary__Property(void *context) { return 0; }
static uint8_t Usr_PowerPage_ESD_Label_1_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_1_Text__Property(void *context) { return "Charge Level : 82%"; }
static uint8_t Usr_PowerPage_ESD_Label_2_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_2_Text__Property(void *context) { return "Charge Rate: 1.3"; }
static uint8_t Usr_PowerPage_ESD_Label_Font__Property(void *context) { return 28; }
static const char * Usr_PowerPage_ESD_Label_Text__Property(void *context) { return "Charge Level : 82%"; }
static const char * Usr_PowerPage_Power_Text__Property(void *context) { return "Power"; }
static ft_bool_t Usr_PowerPage_Power_Primary__Property(void *context) { return 1; }
static Ft_Esd_BitmapCell Usr_PowerPage_Battery_1_BitmapCell__Property(void *context) { return battery_0(); }
static Ft_Esd_BitmapCell Usr_PowerPage_Battery_2_BitmapCell__Property(void *context) { return battery_0(); }
static Ft_Esd_BitmapCell Usr_PowerPage_Battery_3_BitmapCell__Property(void *context) { return battery_0(); }
static Ft_Esd_BitmapCell Usr_PowerPage_Battery_4_BitmapCell__Property(void *context) { return battery_0(); }

static Ft_Esd_WidgetSlots s_Usr_PowerPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_PowerPage_End,
};

static void Usr_PowerPage_Refrigeration_Pushed__Signal(void *context);
static void Usr_PowerPage_Thermal_Pushed__Signal(void *context);
static void Usr_PowerPage_Power_Pushed__Signal(void *context);

void Usr_PowerPage__Fixed_Position__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_PowerPage__Battery_Label_4__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Battery_Label_4;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 762;
	object->Widget.LocalY = 367;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_Battery_Label_4_Font__Property;
	object->Text = Usr_PowerPage_Battery_Label_4_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Battery_Label_3__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Battery_Label_3;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 758;
	object->Widget.LocalY = 87;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_Battery_Label_3_Font__Property;
	object->Text = Usr_PowerPage_Battery_Label_3_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2_2_2_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_2_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 957;
	object->Widget.LocalY = 551;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_2_2_1_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_2_2_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2_2_2__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_2_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 947;
	object->Widget.LocalY = 257;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_2_2_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_2_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Battery_Label_2__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Battery_Label_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 224;
	object->Widget.LocalY = 379;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_Battery_Label_2_Font__Property;
	object->Text = Usr_PowerPage_Battery_Label_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2_1_1_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 953;
	object->Widget.LocalY = 496;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_1_1_1_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_1_1_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2_1_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 945;
	object->Widget.LocalY = 208;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_1_1_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_1_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Battery_Label_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Battery_Label_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 223;
	object->Widget.LocalY = 76;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_Battery_Label_1_Font__Property;
	object->Text = Usr_PowerPage_Battery_Label_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2_2_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 426;
	object->Widget.LocalY = 547;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_2_1_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_2_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_1_2__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 952;
	object->Widget.LocalY = 446;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_1_2_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_1_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 426;
	object->Widget.LocalY = 494;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_1_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Refrigeration__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Refrigeration;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 550;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 250;
	object->Text = Usr_PowerPage_Refrigeration_Text__Property;
	object->Primary = Usr_PowerPage_Refrigeration_Primary__Property;
	object->Pushed = Usr_PowerPage_Refrigeration_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_1_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 943;
	object->Widget.LocalY = 156;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_1_1_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_1_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2_2__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 424;
	object->Widget.LocalY = 255;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_2_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Thermal__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Thermal;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 300;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 250;
	object->Text = Usr_PowerPage_Thermal_Text__Property;
	object->Primary = Usr_PowerPage_Thermal_Primary__Property;
	object->Pushed = Usr_PowerPage_Thermal_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 424;
	object->Widget.LocalY = 444;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_1_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 421;
	object->Widget.LocalY = 204;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 419;
	object->Widget.LocalY = 157;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Power__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Power;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 50;
	object->Widget.LocalWidth = 125;
	object->Widget.LocalHeight = 250;
	object->Text = Usr_PowerPage_Power_Text__Property;
	object->Primary = Usr_PowerPage_Power_Primary__Property;
	object->Pushed = Usr_PowerPage_Power_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Battery_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Battery_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 762;
	object->Widget.LocalY = 413;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = Usr_PowerPage_Battery_1_BitmapCell__Property;
	object->ScaleX = (0L * (1L << 16) + 0x1999L);
	object->ScaleY = (0L * (1L << 16) + 0x1999L);
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Battery_2__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Battery_2;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 759;
	object->Widget.LocalY = 127;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = Usr_PowerPage_Battery_2_BitmapCell__Property;
	object->ScaleX = (0L * (1L << 16) + 0x1999L);
	object->ScaleY = (0L * (1L << 16) + 0x1999L);
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Battery_3__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Battery_3;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 222;
	object->Widget.LocalY = 413;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = Usr_PowerPage_Battery_3_BitmapCell__Property;
	object->ScaleX = (0L * (1L << 16) + 0x1999L);
	object->ScaleY = (0L * (1L << 16) + 0x1999L);
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Battery_4__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Battery_4;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 222;
	object->Widget.LocalY = 131;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = Usr_PowerPage_Battery_4_BitmapCell__Property;
	object->ScaleX = (0L * (1L << 16) + 0x1999L);
	object->ScaleY = (0L * (1L << 16) + 0x1999L);
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_PowerPage_CLASSID;
	context->Widget.Slots = &s_Usr_PowerPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Power_Signal = Esd_Noop;
	context->Thermal_Signal = Esd_Noop;
	context->Refrigeration_Signal = Esd_Noop;
	Usr_PowerPage__Fixed_Position__Initializer(context);
	Usr_PowerPage__Battery_Label_4__Initializer(context);
	Usr_PowerPage__Battery_Label_3__Initializer(context);
	Usr_PowerPage__ESD_Label_2_2_2_1__Initializer(context);
	Usr_PowerPage__ESD_Label_2_2_2__Initializer(context);
	Usr_PowerPage__Battery_Label_2__Initializer(context);
	Usr_PowerPage__ESD_Label_2_1_1_1__Initializer(context);
	Usr_PowerPage__ESD_Label_2_1_1__Initializer(context);
	Usr_PowerPage__Battery_Label_1__Initializer(context);
	Usr_PowerPage__ESD_Label_2_2_1__Initializer(context);
	Usr_PowerPage__ESD_Label_1_2__Initializer(context);
	Usr_PowerPage__ESD_Label_2_1__Initializer(context);
	Usr_PowerPage__Refrigeration__Initializer(context);
	Usr_PowerPage__ESD_Label_1_1__Initializer(context);
	Usr_PowerPage__ESD_Label_2_2__Initializer(context);
	Usr_PowerPage__Thermal__Initializer(context);
	Usr_PowerPage__ESD_Label_1__Initializer(context);
	Usr_PowerPage__ESD_Label_2__Initializer(context);
	Usr_PowerPage__ESD_Label__Initializer(context);
	Usr_PowerPage__Power__Initializer(context);
	Usr_PowerPage__Battery_1__Initializer(context);
	Usr_PowerPage__Battery_2__Initializer(context);
	Usr_PowerPage__Battery_3__Initializer(context);
	Usr_PowerPage__Battery_4__Initializer(context);
}

void Usr_PowerPage_End(Usr_PowerPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Battery_Label_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Battery_Label_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_2_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_2_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Battery_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Battery_Label_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Refrigeration); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Thermal); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Power); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Battery_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Battery_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Battery_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Battery_4); 
}

void Usr_PowerPage_Refrigeration_Pushed__Signal(void *c)
{
	Usr_PowerPage *context = (Usr_PowerPage *)c;
	void *owner = context->Owner;
	context->Refrigeration_Signal(owner);
}

void Usr_PowerPage_Thermal_Pushed__Signal(void *c)
{
	Usr_PowerPage *context = (Usr_PowerPage *)c;
	void *owner = context->Owner;
	context->Thermal_Signal(owner);
}

void Usr_PowerPage_Power_Pushed__Signal(void *c)
{
	Usr_PowerPage *context = (Usr_PowerPage *)c;
	void *owner = context->Owner;
	context->Power_Signal(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_PowerPage Instance;
} Usr_PowerPage__ESD;


void *Usr_PowerPage__Create__ESD()
{
	Usr_PowerPage__ESD *context = (Usr_PowerPage__ESD *)esd_malloc(sizeof(Usr_PowerPage__ESD));
	if (context)
	{
		Usr_PowerPage__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_PowerPage__Create__ESD)");
	}
	return context;
}

void Usr_PowerPage__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
