/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_ManagementPage
Header
*/

#ifndef Usr_ManagementPage__H
#define Usr_ManagementPage__H

#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_ManagementPage_CLASSID 0x5F3FC30F
ESD_SYMBOL(Usr_ManagementPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_ManagementPage, Include = "Usr_ManagementPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
} Usr_ManagementPage;

void Usr_ManagementPage__Initializer(Usr_ManagementPage *context);

#endif /* Usr_ManagementPage__H */

/* end of file */
