/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_HeaderPage
C Source
*/

#include "Usr_HeaderPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static Ft_Esd_Theme * Usr_HeaderPage_Conflicts_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static const char * Usr_HeaderPage_Conflicts_Text__Property(void *context) { return "Conflicts"; }
static ft_bool_t Usr_HeaderPage_Conflicts_Primary__Property(void *context);
static Ft_Esd_Theme * Usr_HeaderPage_Management_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static const char * Usr_HeaderPage_Management_Text__Property(void *context) { return "Management"; }
static ft_bool_t Usr_HeaderPage_Management_Primary__Property(void *context);
static Ft_Esd_Theme * Usr_HeaderPage_Status_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static const char * Usr_HeaderPage_Status_Text__Property(void *context) { return "Status"; }
static ft_bool_t Usr_HeaderPage_Status_Primary__Property(void *context);
static Ft_Esd_Theme * Usr_HeaderPage_Items_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static const char * Usr_HeaderPage_Items_Text__Property(void *context) { return "Items"; }
static ft_bool_t Usr_HeaderPage_Items_Primary__Property(void *context);
static Ft_Esd_Theme * Usr_HeaderPage_Dashboard_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static const char * Usr_HeaderPage_Dashboard_Text__Property(void *context) { return "Dashboard"; }
static ft_bool_t Usr_HeaderPage_Dashboard_Primary__Property(void *context);

static Ft_Esd_WidgetSlots s_Usr_HeaderPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_HeaderPage_End,
};

static void Usr_HeaderPage_Conflicts_Pushed__Signal(void *context);
static void Usr_HeaderPage_Management_Pushed__Signal(void *context);
static void Usr_HeaderPage_Status_Pushed__Signal(void *context);
static void Usr_HeaderPage_Items_Pushed__Signal(void *context);
static void Usr_HeaderPage_Dashboard_Pushed__Signal(void *context);

void Usr_HeaderPage__Fixed_Position__Initializer(Usr_HeaderPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_HeaderPage__Conflicts__Initializer(Usr_HeaderPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Conflicts;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 512;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 256;
	object->Widget.LocalHeight = 50;
	object->Theme = Usr_HeaderPage_Conflicts_Theme__Property;
	object->Text = Usr_HeaderPage_Conflicts_Text__Property;
	object->Primary = Usr_HeaderPage_Conflicts_Primary__Property;
	object->Pushed = Usr_HeaderPage_Conflicts_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeaderPage__Management__Initializer(Usr_HeaderPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Management;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 1024;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 256;
	object->Widget.LocalHeight = 50;
	object->Theme = Usr_HeaderPage_Management_Theme__Property;
	object->Text = Usr_HeaderPage_Management_Text__Property;
	object->Primary = Usr_HeaderPage_Management_Primary__Property;
	object->Pushed = Usr_HeaderPage_Management_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeaderPage__Status__Initializer(Usr_HeaderPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Status;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 768;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 256;
	object->Widget.LocalHeight = 50;
	object->Theme = Usr_HeaderPage_Status_Theme__Property;
	object->Text = Usr_HeaderPage_Status_Text__Property;
	object->Primary = Usr_HeaderPage_Status_Primary__Property;
	object->Pushed = Usr_HeaderPage_Status_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeaderPage__Items__Initializer(Usr_HeaderPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Items;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 256;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 256;
	object->Widget.LocalHeight = 50;
	object->Theme = Usr_HeaderPage_Items_Theme__Property;
	object->Text = Usr_HeaderPage_Items_Text__Property;
	object->Primary = Usr_HeaderPage_Items_Primary__Property;
	object->Pushed = Usr_HeaderPage_Items_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeaderPage__Dashboard__Initializer(Usr_HeaderPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Dashboard;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 256;
	object->Widget.LocalHeight = 50;
	object->Theme = Usr_HeaderPage_Dashboard_Theme__Property;
	object->Text = Usr_HeaderPage_Dashboard_Text__Property;
	object->Primary = Usr_HeaderPage_Dashboard_Primary__Property;
	object->Pushed = Usr_HeaderPage_Dashboard_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeaderPage__Initializer(Usr_HeaderPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_HeaderPage_CLASSID;
	context->Widget.Slots = &s_Usr_HeaderPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Management_Signal = Esd_Noop;
	context->Status_Signal = Esd_Noop;
	context->Conflicts_Signal = Esd_Noop;
	context->Dashboard_Signal = Esd_Noop;
	context->Items_Signal = Esd_Noop;
	context->Selected_Page = 0L;
	Usr_HeaderPage__Fixed_Position__Initializer(context);
	Usr_HeaderPage__Conflicts__Initializer(context);
	Usr_HeaderPage__Management__Initializer(context);
	Usr_HeaderPage__Status__Initializer(context);
	Usr_HeaderPage__Items__Initializer(context);
	Usr_HeaderPage__Dashboard__Initializer(context);
}

void Usr_HeaderPage_End(Usr_HeaderPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Conflicts); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Management); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Status); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Items); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Dashboard); 
}

ft_bool_t Usr_HeaderPage_Conflicts_Primary__Property(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	int left = context->Selected_Page;
	int right = 2L;
	return left == right;
}

void Usr_HeaderPage_Conflicts_Pushed__Signal(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	context->Conflicts_Signal(owner);
	int set_variable_3 = 2L;
	context->Selected_Page = set_variable_3;
}

ft_bool_t Usr_HeaderPage_Management_Primary__Property(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	int left_1 = context->Selected_Page;
	int right_1 = 4L;
	return left_1 == right_1;
}

void Usr_HeaderPage_Management_Pushed__Signal(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	context->Management_Signal(owner);
	int set_variable_5 = 4L;
	context->Selected_Page = set_variable_5;
}

ft_bool_t Usr_HeaderPage_Status_Primary__Property(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	int left_2 = context->Selected_Page;
	int right_2 = 3L;
	return left_2 == right_2;
}

void Usr_HeaderPage_Status_Pushed__Signal(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	context->Status_Signal(owner);
	int set_variable_4 = 3L;
	context->Selected_Page = set_variable_4;
}

ft_bool_t Usr_HeaderPage_Items_Primary__Property(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	int left_3 = context->Selected_Page;
	int right_3 = 1L;
	return left_3 == right_3;
}

void Usr_HeaderPage_Items_Pushed__Signal(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	context->Items_Signal(owner);
	int set_variable_2 = 1L;
	context->Selected_Page = set_variable_2;
}

ft_bool_t Usr_HeaderPage_Dashboard_Primary__Property(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	int left_4 = context->Selected_Page;
	int right_4 = 0L;
	return left_4 == right_4;
}

void Usr_HeaderPage_Dashboard_Pushed__Signal(void *c)
{
	Usr_HeaderPage *context = (Usr_HeaderPage *)c;
	void *owner = context->Owner;
	context->Dashboard_Signal(owner);
	int set_variable = 0L;
	context->Selected_Page = set_variable;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_HeaderPage Instance;
} Usr_HeaderPage__ESD;


void *Usr_HeaderPage__Create__ESD()
{
	Usr_HeaderPage__ESD *context = (Usr_HeaderPage__ESD *)esd_malloc(sizeof(Usr_HeaderPage__ESD));
	if (context)
	{
		Usr_HeaderPage__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_HeaderPage__Create__ESD)");
	}
	return context;
}

void Usr_HeaderPage__Destroy__ESD(void *context)
{
	esd_free(context);
}

void Usr_HeaderPage__Set_Selected_Page__ESD(void *context, int value) { ((Usr_HeaderPage__ESD *)context)->Instance.Selected_Page = value; }

#endif /* ESD_SIMULATION */

/* end of file */
