/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_StatusPage
Header
*/

#ifndef Usr_StatusPage__H
#define Usr_StatusPage__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"
#include "Usr_RowWidget.h"
#include "Usr_ScrollPanelVert.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_StatusPage_CLASSID 0x75A526BC
ESD_SYMBOL(Usr_StatusPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_StatusPage, Include = "Usr_StatusPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(Back_Signal)
	void(* Back_Signal)(void *context);
	ESD_SIGNAL(Power_Signal)
	void(* Power_Signal)(void *context);
	ESD_SIGNAL(Thermal_Signal)
	void(* Thermal_Signal)(void *context);
	ESD_SIGNAL(Refrigeration_Signal)
	void(* Refrigeration_Signal)(void *context);
	Ft_Esd_Layout_Fixed Fixed_Position;
	Usr_ScrollPanelVert Vertical_Scroll_Panel;
	Usr_RowWidget Usr_RowWidget;
	Ft_Esd_PushButton Refrigeration;
	Ft_Esd_PushButton Thermal;
	Ft_Esd_PushButton Power;
	Ft_Esd_PushButton Back_Button;
} Usr_StatusPage;

void Usr_StatusPage__Initializer(Usr_StatusPage *context);

ESD_SLOT(End)
void Usr_StatusPage_End(Usr_StatusPage *context);

#endif /* Usr_StatusPage__H */

/* end of file */
