/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_PowerPage
Header
*/

#ifndef Usr_PowerPage__H
#define Usr_PowerPage__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_Image.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"
#include "battery.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_PowerPage_CLASSID 0x67C3979A
ESD_SYMBOL(Usr_PowerPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_PowerPage, Include = "Usr_PowerPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(Power_Signal)
	void(* Power_Signal)(void *context);
	ESD_SIGNAL(Thermal_Signal)
	void(* Thermal_Signal)(void *context);
	ESD_SIGNAL(Refrigeration_Signal)
	void(* Refrigeration_Signal)(void *context);
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_Label Battery_Label_4;
	Ft_Esd_Label Battery_Label_3;
	Ft_Esd_Label ESD_Label_2_2_2_1;
	Ft_Esd_Label ESD_Label_2_2_2;
	Ft_Esd_Label Battery_Label_2;
	Ft_Esd_Label ESD_Label_2_1_1_1;
	Ft_Esd_Label ESD_Label_2_1_1;
	Ft_Esd_Label Battery_Label_1;
	Ft_Esd_Label ESD_Label_2_2_1;
	Ft_Esd_Label ESD_Label_1_2;
	Ft_Esd_Label ESD_Label_2_1;
	Ft_Esd_PushButton Refrigeration;
	Ft_Esd_Label ESD_Label_1_1;
	Ft_Esd_Label ESD_Label_2_2;
	Ft_Esd_PushButton Thermal;
	Ft_Esd_Label ESD_Label_1;
	Ft_Esd_Label ESD_Label_2;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_PushButton Power;
	Ft_Esd_Image Battery_1;
	Ft_Esd_Image Battery_2;
	Ft_Esd_Image Battery_3;
	Ft_Esd_Image Battery_4;
} Usr_PowerPage;

void Usr_PowerPage__Initializer(Usr_PowerPage *context);

ESD_SLOT(End)
void Usr_PowerPage_End(Usr_PowerPage *context);

#endif /* Usr_PowerPage__H */

/* end of file */
