/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_NumKeyboard
C Source
*/

#include "Usr_NumKeyboard.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Usr_NumKeyboard__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Usr_NumKeyboard_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_NumKeyboard_Update,
	(void(*)(void *))Usr_NumKeyboard_Render,
	(void(*)(void *))Usr_NumKeyboard_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_NumKeyboard_End,
};


void Usr_NumKeyboard__Linear_Layout__Initializer(Usr_NumKeyboard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 162;
	object->Widget.LocalY = 84;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Align = ESD_ALIGN_FILLFILL;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_NumKeyboard__ESD_Numeric_Label__Initializer(Usr_NumKeyboard *context)
{
	Ft_Esd_NumericLabel *object = (Ft_Esd_NumericLabel *)&context->ESD_Numeric_Label;
	Ft_Esd_NumericLabel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 552;
	object->Widget.LocalY = 265;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void Usr_NumKeyboard__Linear_Layout_2__Initializer(Usr_NumKeyboard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 485;
	object->Widget.LocalY = 338;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_FILLFILL;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void Usr_NumKeyboard__Linear_Layout_3__Initializer(Usr_NumKeyboard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 550;
	object->Widget.LocalY = 158;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_FILLFILL;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void Usr_NumKeyboard__Initializer(Usr_NumKeyboard *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_NumKeyboard_CLASSID;
	context->Widget.Slots = &s_Usr_NumKeyboard__Slots;
	context->Widget.LocalX = 4;
	context->Widget.LocalY = -1;
	context->Widget.LocalWidth = 750;
	context->Widget.LocalHeight = 660;
	Usr_NumKeyboard__Linear_Layout__Initializer(context);
	Usr_NumKeyboard__ESD_Numeric_Label__Initializer(context);
	Usr_NumKeyboard__Linear_Layout_2__Initializer(context);
	Usr_NumKeyboard__Linear_Layout_3__Initializer(context);
}

void Usr_NumKeyboard_End__Builtin(Usr_NumKeyboard *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Numeric_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3); 
}

void Usr_NumKeyboard_Start(Usr_NumKeyboard *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
}

void Usr_NumKeyboard_Update(Usr_NumKeyboard *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void Usr_NumKeyboard_Render(Usr_NumKeyboard *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Usr_NumKeyboard_Idle(Usr_NumKeyboard *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Idle((Ft_Esd_Widget *)context); 
}

void Usr_NumKeyboard_End(Usr_NumKeyboard *context)
{
	void *owner = context->Owner;
	Usr_NumKeyboard_End__Builtin(context);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_NumKeyboard Instance;
} Usr_NumKeyboard__ESD;


void *Usr_NumKeyboard__Create__ESD()
{
	Usr_NumKeyboard__ESD *context = (Usr_NumKeyboard__ESD *)esd_malloc(sizeof(Usr_NumKeyboard__ESD));
	if (context)
	{
		Usr_NumKeyboard__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_NumKeyboard__Create__ESD)");
	}
	return context;
}

void Usr_NumKeyboard__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
