/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_NumKeyboard
Header
*/

#ifndef Usr_NumKeyboard__H
#define Usr_NumKeyboard__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Layout_Linear.h"
#include "Ft_Esd_Math.h"
#include "Ft_Esd_NumericLabel.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_NumKeyboard_CLASSID 0x5A726718
ESD_SYMBOL(Usr_NumKeyboard_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_NumKeyboard, Include = "Usr_NumKeyboard.h", Callback, X = 4, Y = -1, Width = 750, Height = 660)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	Ft_Esd_Layout_Linear Linear_Layout;
	Ft_Esd_NumericLabel ESD_Numeric_Label;
	Ft_Esd_Layout_Linear Linear_Layout_2;
	Ft_Esd_Layout_Linear Linear_Layout_3;
} Usr_NumKeyboard;

void Usr_NumKeyboard__Initializer(Usr_NumKeyboard *context);

ESD_SLOT(Start)
void Usr_NumKeyboard_Start(Usr_NumKeyboard *context);

ESD_SLOT(Update)
void Usr_NumKeyboard_Update(Usr_NumKeyboard *context);

ESD_SLOT(Render)
void Usr_NumKeyboard_Render(Usr_NumKeyboard *context);

ESD_SLOT(Idle)
void Usr_NumKeyboard_Idle(Usr_NumKeyboard *context);

ESD_SLOT(End)
void Usr_NumKeyboard_End(Usr_NumKeyboard *context);

#endif /* Usr_NumKeyboard__H */

/* end of file */
